version: '3.8'

x-app: &app
  image: hmis-warehouse:4.0
  stdin_open: true
  tty: true
  build:
    context: ../..
    dockerfile: docker/app/Dockerfile
    args:
      BUILD_TAG: 3.1.6-alpine3.18
      USER_ID: ${USER_ID:-1001}
      GROUP_ID: ${GROUP_ID:-1001}
      #RUBY_VERSION: 3.1.6
      BUNDLER_VERSION: '2.4.13'
      GITHASH: 12345

services:
  run:
    <<: *app
