// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or rename an existing controller

import { application } from "./application"

import DatepickerController from "./datepicker_controller.js"
application.register("datepicker", DatepickerController)
