FROM open-path-warehouse:latest--base

LABEL "role"=web

HEALTHCHECK --start-period=15s --interval=5m --timeout=10s \
  CMD curl -k -f https://localhost:3000/system_status/operational || exit 1

EXPOSE 3000

# Start the main process.
CMD [ "puma", "-b", "ssl://0.0.0.0:3000?key=/app/config/key.pem&cert=/app/config/cert.pem&verify_mode=none" ]
