SELECT "ExportID",
    "SourceID",
    "SourceName",
    "SourceContactFirst",
    "SourceContactLast",
    "SourceContactPhone",
    "SourceContactExtension",
    "SourceContactEmail",
    "ExportDate",
    "ExportStartDate",
    "ExportEndDate",
    "SoftwareName",
    "SoftwareVersion",
    "ExportPeriodType",
    "ExportDirective",
    "HashStatus",
    data_source_id,
    id,
    "SourceType",
    effective_export_end_date,
    source_hash,
    "CSVVersion",
    "ImplementationID"
   FROM "Export"