SELECT "HealthAndDVID",
    "EnrollmentID",
    "PersonalID",
    "InformationDate",
    "DomesticViolenceVictim",
    "WhenOccurred",
    "CurrentlyFleeing",
    "GeneralHealthStatus",
    "DentalHealthStatus",
    "MentalHealthStatus",
    "PregnancyStatus",
    "DueDate",
    "DataCollectionStage",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    id,
    source_hash,
    pending_date_deleted,
    "LifeValue",
    "SupportFromOthers",
    "BounceBack",
    "FeelingFrequency",
    "DomesticViolenceSurvivor"
   FROM "HealthAndDV"
  WHERE ("DateDeleted" IS NULL)