 SELECT "ProjectID",
    "OrganizationID",
    "ProjectName",
    "ProjectCommonName",
    "ContinuumProject",
    "ProjectType",
    "ResidentialAffiliation",
    "TrackingMethod",
    "TargetPopulation",
    "PITCount",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    id,
    confidential,
    computed_project_type,
    "OperatingStartDate",
    "OperatingEndDate",
    "VictimServicesProvider",
    "HousingType",
    local_planning_group,
    source_hash,
    uses_move_in_date,
    pending_date_deleted,
    "HMISParticipatingProject",
    active_homeless_status_override,
    include_in_days_homeless_override,
    extrapolate_contacts,
    combine_enrollments,
    "HOPWAMedAssistedLivingFac",
    description,
    contact_information,
    "RRHSubType"
   FROM public."Project"
  WHERE ("DateDeleted" IS NULL)
