SELECT id,
    enrollment_coc_id,
    health_and_dv_id,
    income_benefit_id,
    physical_disability_id,
    developmental_disability_id,
    chronic_health_condition_id,
    hiv_aids_id,
    mental_health_disorder_id,
    substance_use_disorder_id,
    exit_id,
    custom_assessment_id,
    definition_id,
    "values",
    hud_values,
    youth_education_status_id,
    employment_education_id,
    current_living_situation_id,
    ce_assessment_id,
    ce_event_id,
    owner_type,
    owner_id,
    backup_values,
    clh_location_id
   FROM hmis_form_processors