SELECT "DisabilitiesID",
    "EnrollmentID",
    "PersonalID",
    "InformationDate",
    "DisabilityType",
    "DisabilityResponse",
    "IndefiniteAndImpairs",
    "DocumentationOnFile",
    "ReceivingServices",
    "PATHHowConfirmed",
    "PATHSMIInformation",
    "TCellCountAvailable",
    "TCellCount",
    "TCellSource",
    "ViralLoadAvailable",
    "ViralLoad",
    "ViralLoadSource",
    "DataCollectionStage",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    id,
    source_hash,
    pending_date_deleted,
    "AntiRetroviral"
   FROM "Disabilities"
  WHERE ("DateDeleted" IS NULL)