 SELECT "InventoryID",
    "ProjectID",
    "CoCCode",
    "InformationDate",
    "HouseholdType",
    "BedType",
    "Availability",
    "UnitInventory",
    "BedInventory",
    "CHBedInventory",
    "VetBedInventory",
    "YouthBedInventory",
    "YouthAgeGroup",
    "InventoryStartDate",
    "InventoryEndDate",
    "HMISParticipatingBeds",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    id,
    source_hash,
    pending_date_deleted,
    "CHVetBedInventory",
    "YouthVetBedInventory",
    "CHYouthBedInventory",
    "OtherBedInventory",
    "TargetPopulation",
    "ESBedType",
    manual_entry
   FROM public."Inventory"
  WHERE ("DateDeleted" IS NULL)
