SELECT id,
    use,
    address_type,
    line1,
    line2,
    city,
    state,
    district,
    country,
    postal_code,
    notes,
    "AddressID",
    "PersonalID",
    "UserID",
    data_source_id,
    "DateCreated",
    "DateUpdated",
    "DateDeleted",
    "EnrollmentID",
    enrollment_address_type
   FROM "CustomClientAddress"
  WHERE ("DateDeleted" IS NULL)