SELECT id,
    "AssessmentID",
    "EnrollmentID",
    "PersonalID",
    "AssessmentDate",
    "AssessmentLocation",
    "AssessmentType",
    "AssessmentLevel",
    "PrioritizationStatus",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    pending_date_deleted,
    source_hash,
    synthetic
   FROM "Assessment"
  WHERE ("DateDeleted" IS NULL)