 SELECT "ProjectCoCID",
    "ProjectID",
    "CoCCode",
    "DateCreated",
    "DateUpdated",
    "UserID",
    "DateDeleted",
    "ExportID",
    data_source_id,
    id,
    hud_coc_code,
    source_hash,
    pending_date_deleted,
    "Geocode",
    "GeographyType",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zip",
    geography_type_override,
    geocode_override,
    zip_override,
    manual_entry
   FROM public."ProjectCoC"
  WHERE ("DateDeleted" IS NULL)
