SELECT
  "ExitID",
  "EnrollmentID",
  "PersonalID",
  "ExitDate",
  "Destination",
  "OtherDestination",
  -- these as they are from an old version of the HUD spec
  -- "AssessmentDisposition",
  -- "OtherDisposition",
  "HousingAssessment",
  "SubsidyInformation",
  -- not sure why its on the Exit table, this is a field on IncomeBenefit
  -- "ConnectionWithSOAR",
  -- these are not in the current version of the HUD Spec, they are likely from old versions
  -- "WrittenAftercarePlan",
  -- "AssistanceMainstreamBenefits",
  -- "PermanentHousingPlacement",
  -- "TemporaryShelterPlacement",
  -- "ExitCounseling",
  -- "FurtherFollowUpServices",
  -- "ScheduledFollowUpContacts",
  -- "ResourcePackage",
  -- "OtherAftercarePlanOrAction",
  "ProjectCompletionStatus",
  "EarlyExitReason",
  -- from old hud spec, has been retired
  -- "FamilyReunificationAchieved",
  "DateCreated",
  "DateUpdated",
  "UserID",
  --"DateDeleted",
  "ExportID",
  data_source_id,
  id,
  "ExchangeForSex",
  "ExchangeForSexPastThreeMonths",
  "CountOfExchangeForSex",
  "AskedOrForcedToExchangeForSex",
  "AskedOrForcedToExchangeForSexPastThreeMonths",
  "WorkPlaceViolenceThreats",
  "WorkplacePromiseDifference",
  "CoercedToContinueWork",
  "LaborExploitPastThreeMonths",
  "CounselingReceived",
  "IndividualCounseling",
  "FamilyCounseling",
  "GroupCounseling",
  "SessionCountAtExit",
  "PostExitCounselingPlan",
  "SessionsInPlan",
  "DestinationSafeClient",
  "DestinationSafeWorker",
  "PosAdultConnections",
  "PosPeerConnections",
  "PosCommunityConnections",
  "AftercareDate",
  "AftercareProvided",
  "EmailSocialMedia",
  "Telephone",
  "InPersonIndividual",
  "InPersonGroup",
  "CMExitReason",
  "DestinationSubsidyType",
  auto_exited,
  (auto_exited IS NOT NULL) AS is_auto_exited
FROM
  public."Exit"
WHERE
  ("DateDeleted" IS NULL);
