
      SELECT "Exit"."ExitID",
      "Exit"."EnrollmentID" AS "ProjectEntryID",
      "Exit"."PersonalID",
      "Exit"."ExitDate",
      "Exit"."Destination",
      "Exit"."OtherDestination",
      "Exit"."AssessmentDisposition",
      "Exit"."OtherDisposition",
      "Exit"."HousingAssessment",
      "Exit"."SubsidyInformation",
      "Exit"."ConnectionWithSOAR",
      "Exit"."WrittenAftercarePlan",
      "Exit"."AssistanceMainstreamBenefits",
      "Exit"."PermanentHousingPlacement",
      "Exit"."TemporaryShelterPlacement",
      "Exit"."ExitCounseling",
      "Exit"."FurtherFollowUpServices",
      "Exit"."ScheduledFollowUpContacts",
      "Exit"."ResourcePackage",
      "Exit"."OtherAftercarePlanOrAction",
      "Exit"."ProjectCompletionStatus",
      "Exit"."EarlyExitReason",
      "Exit"."FamilyReunificationAchieved",
      "Exit"."DateCreated",
      "Exit"."DateUpdated",
      "Exit"."UserID",
      "Exit"."DateDeleted",
      "Exit"."ExportID",
      "Exit".data_source_id,
      "Exit".id,
      "Exit"."ExchangeForSex",
      "Exit"."ExchangeForSexPastThreeMonths",
      "Exit"."CountOfExchangeForSex",
      "Exit"."AskedOrForcedToExchangeForSex",
      "Exit"."AskedOrForcedToExchangeForSexPastThreeMonths",
      "Exit"."WorkPlaceViolenceThreats",
      "Exit"."WorkplacePromiseDifference",
      "Exit"."CoercedToContinueWork",
      "Exit"."LaborExploitPastThreeMonths",
      "Exit"."CounselingReceived",
      "Exit"."IndividualCounseling",
      "Exit"."FamilyCounseling",
      "Exit"."GroupCounseling",
      "Exit"."SessionCountAtExit",
      "Exit"."PostExitCounselingPlan",
      "Exit"."SessionsInPlan",
      "Exit"."DestinationSafeClient",
      "Exit"."DestinationSafeWorker",
      "Exit"."PosAdultConnections",
      "Exit"."PosPeerConnections",
      "Exit"."PosCommunityConnections",
      "Exit"."AftercareDate",
      "Exit"."AftercareProvided",
      "Exit"."EmailSocialMedia",
      "Exit"."Telephone",
      "Exit"."InPersonIndividual",
      "Exit"."InPersonGroup",
      "Exit"."CMExitReason",
      "Enrollment".id AS enrollment_id,
      source_clients.id AS demographic_id,
      destination_clients.id AS client_id
     FROM (((("Exit"
       JOIN "Client" source_clients ON ((("Exit".data_source_id = source_clients.data_source_id) AND (("Exit"."PersonalID")::text = (source_clients."PersonalID")::text) AND (source_clients."DateDeleted" IS NULL))))
       JOIN warehouse_clients ON ((source_clients.id = warehouse_clients.source_id)))
       JOIN "Client" destination_clients ON (((destination_clients.id = warehouse_clients.destination_id) AND (destination_clients."DateDeleted" IS NULL))))
       JOIN "Enrollment" ON ((("Exit".data_source_id = "Enrollment".data_source_id) AND (("Exit"."PersonalID")::text = ("Enrollment"."PersonalID")::text) AND (("Exit"."EnrollmentID")::text = ("Enrollment"."EnrollmentID")::text) AND ("Enrollment"."DateDeleted" IS NULL))))
    WHERE ("Exit"."DateDeleted" IS NULL);
