      SELECT "Enrollment"."EnrollmentID" AS "ProjectEntryID",
      "Enrollment"."PersonalID",
      "Enrollment"."ProjectID",
      "Enrollment"."EntryDate",
      "Enrollment"."HouseholdID",
      "Enrollment"."RelationshipToHoH",
      "Enrollment"."LivingSituation" AS "ResidencePrior",
      "Enrollment"."OtherResidencePrior",
      "Enrollment"."LengthOfStay" AS "ResidencePriorLengthOfStay",
      "Enrollment"."DisablingCondition",
      "Enrollment"."EntryFromStreetESSH",
      "Enrollment"."DateToStreetESSH",
      "Enrollment"."ContinuouslyHomelessOneYear",
      "Enrollment"."TimesHomelessPastThreeYears",
      "Enrollment"."MonthsHomelessPastThreeYears",
      "Enrollment"."MonthsHomelessThisTime",
      "Enrollment"."StatusDocumented",
      "Enrollment"."HousingStatus",
      "Enrollment"."DateOfEngagement",
      "Enrollment"."InPermanentHousing",
      "Enrollment"."MoveInDate" AS "ResidentialMoveInDate",
      "Enrollment"."DateOfPATHStatus",
      "Enrollment"."ClientEnrolledInPATH",
      "Enrollment"."ReasonNotEnrolled",
      "Enrollment"."WorstHousingSituation",
      "Enrollment"."PercentAMI",
      "Enrollment"."LastPermanentStreet",
      "Enrollment"."LastPermanentCity",
      "Enrollment"."LastPermanentState",
      "Enrollment"."LastPermanentZIP",
      "Enrollment"."AddressDataQuality",
      "Enrollment"."DateOfBCPStatus",
      "Enrollment"."EligibleForRHY" AS "FYSBYouth",
      "Enrollment"."ReasonNoServices",
      "Enrollment"."SexualOrientation",
      "Enrollment"."FormerWardChildWelfare",
      "Enrollment"."ChildWelfareYears",
      "Enrollment"."ChildWelfareMonths",
      "Enrollment"."FormerWardJuvenileJustice",
      "Enrollment"."JuvenileJusticeYears",
      "Enrollment"."JuvenileJusticeMonths",
      "Enrollment"."HouseholdDynamics",
      "Enrollment"."SexualOrientationGenderIDYouth",
      "Enrollment"."SexualOrientationGenderIDFam",
      "Enrollment"."HousingIssuesYouth",
      "Enrollment"."HousingIssuesFam",
      "Enrollment"."SchoolEducationalIssuesYouth",
      "Enrollment"."SchoolEducationalIssuesFam",
      "Enrollment"."UnemploymentYouth",
      "Enrollment"."UnemploymentFam",
      "Enrollment"."MentalHealthIssuesYouth",
      "Enrollment"."MentalHealthIssuesFam",
      "Enrollment"."HealthIssuesYouth",
      "Enrollment"."HealthIssuesFam",
      "Enrollment"."PhysicalDisabilityYouth",
      "Enrollment"."PhysicalDisabilityFam",
      "Enrollment"."MentalDisabilityYouth",
      "Enrollment"."MentalDisabilityFam",
      "Enrollment"."AbuseAndNeglectYouth",
      "Enrollment"."AbuseAndNeglectFam",
      "Enrollment"."AlcoholDrugAbuseYouth",
      "Enrollment"."AlcoholDrugAbuseFam",
      "Enrollment"."InsufficientIncome",
      "Enrollment"."ActiveMilitaryParent",
      "Enrollment"."IncarceratedParent",
      "Enrollment"."IncarceratedParentStatus",
      "Enrollment"."ReferralSource",
      "Enrollment"."CountOutreachReferralApproaches",
      "Enrollment"."ExchangeForSex",
      "Enrollment"."ExchangeForSexPastThreeMonths",
      "Enrollment"."CountOfExchangeForSex",
      "Enrollment"."AskedOrForcedToExchangeForSex",
      "Enrollment"."AskedOrForcedToExchangeForSexPastThreeMonths",
      "Enrollment"."WorkPlaceViolenceThreats",
      "Enrollment"."WorkplacePromiseDifference",
      "Enrollment"."CoercedToContinueWork",
      "Enrollment"."LaborExploitPastThreeMonths",
      "Enrollment"."HPScreeningScore",
      "Enrollment"."VAMCStation_deleted" AS "VAMCStation",
      "Enrollment"."DateCreated",
      "Enrollment"."DateUpdated",
      "Enrollment"."UserID",
      "Enrollment"."DateDeleted",
      "Enrollment"."ExportID",
      "Enrollment".data_source_id,
      "Enrollment".id,
      "Enrollment"."LOSUnderThreshold",
      "Enrollment"."PreviousStreetESSH",
      "Enrollment"."UrgentReferral",
      "Enrollment"."TimeToHousingLoss",
      "Enrollment"."ZeroIncome",
      "Enrollment"."AnnualPercentAMI",
      "Enrollment"."FinancialChange",
      "Enrollment"."HouseholdChange",
      "Enrollment"."EvictionHistory",
      "Enrollment"."SubsidyAtRisk",
      "Enrollment"."LiteralHomelessHistory",
      "Enrollment"."DisabledHoH",
      "Enrollment"."CriminalRecord",
      "Enrollment"."SexOffender",
      "Enrollment"."DependentUnder6",
      "Enrollment"."SingleParent",
      "Enrollment"."HH5Plus",
      "Enrollment"."IraqAfghanistan",
      "Enrollment"."FemVet",
      "Enrollment"."ThresholdScore",
      "Enrollment"."ERVisits",
      "Enrollment"."JailNights",
      "Enrollment"."HospitalNights",
      "Enrollment"."RunawayYouth",
      "Enrollment".processed_hash,
      source_clients.id AS demographic_id,
      destination_clients.id AS client_id
     FROM ((("Enrollment"
       JOIN "Client" source_clients ON ((("Enrollment".data_source_id = source_clients.data_source_id) AND (("Enrollment"."PersonalID")::text = (source_clients."PersonalID")::text) AND (source_clients."DateDeleted" IS NULL))))
       JOIN warehouse_clients ON ((source_clients.id = warehouse_clients.source_id)))
       JOIN "Client" destination_clients ON (((destination_clients.id = warehouse_clients.destination_id) AND (destination_clients."DateDeleted" IS NULL))))
    WHERE ("Enrollment"."DateDeleted" IS NULL);
