      SELECT "GeographyID",
      "ProjectID",
      "CoCCode",
      "PrincipalSite",
      "Geocode",
      "Address1",
      "City",
      "State",
      "ZIP",
      "DateCreated",
      "DateUpdated",
      "UserID",
      "DateDeleted",
      "ExportID",
      data_source_id,
      id,
      "InformationDate",
      "Address2",
      "GeographyType",
      source_hash
     FROM "Geography";
