###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomDataElementDefinition < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_data_element_definitions'
    self.hud_key = :CustomDataElementDefinitionID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomDataElementDefinition.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:CustomDataElementDefinitionID, 'CustomDataElementDefinition')

    # Validations
    validates :CustomDataElementDefinitionID, presence: true
    validates :Key, presence: true
    validates :RecordType, presence: true
    validates :RecordType, inclusion: { in: ['Client', 'Enrollment', 'Exit', 'Project', 'Organization'] }
    validates :FieldType, presence: true
    validates :FieldType, inclusion: { in: ['string', 'integer', 'date', 'boolean', 'text'] }
    validates :Label, presence: true
    validates :Label, length: { maximum: 255 }
    validates :Repeats, presence: true
    validates :Repeats, inclusion: { in: [true, false, 0, 1, '0', '1', 'true', 'false'] }, allow_blank: true
  end
end
