###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomDataElement < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_data_elements'
    self.hud_key = :CustomDataElementID
    @custom_file_config = HmisCsvTwentyTwentySix.custom_files_config.for('CustomDataElement.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:CustomDataElementID, 'CustomDataElement')

    # Validations
    validates :CustomDataElementID, presence: true
    validates :CustomDataElementDefinitionID, presence: true
    validates :RecordType, presence: true
    validates :RecordType, inclusion: { in: ['Client', 'Enrollment', 'Exit', 'Project', 'Organization'] }
    validates :RecordID, presence: true
    validates :DataCollectionStage, numericality: { only_integer: true }, allow_blank: true
  end
end
