###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomDataElement < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_data_elements'
    self.hud_key = :CustomDataElementID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomDataElement.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:CustomDataElementID, 'CustomDataElement')

    # Validations
    validates :CustomDataElementID, presence: true
    validates :CustomDataElementDefinitionID, presence: true
    validates :RecordType, presence: true
    validates :RecordType, inclusion: { in: ['Client', 'Enrollment', 'Exit', 'Project', 'Organization'] }
    validates :RecordID, presence: true
    validates :DataCollectionStage, numericality: { only_integer: true }, allow_blank: true

    def self.hmis_configuration(version: '2026')
  {
        CustomDataElementID: { type: :string, null: false },
        CustomDataElementDefinitionID: { type: :string, null: false },
        RecordType: { type: :string, null: false },
        RecordID: { type: :string, null: false },
        Value: { type: :string },
        DataCollectionStage: { type: :integer },
        InformationDate: { type: :date },
        UserID: { type: :string },
        DateCreated: { type: :datetime },
        DateUpdated: { type: :datetime },
        DateDeleted: { type: :datetime },
        ExportID: { type: :string },
        _data_element_definition_id_default: { type: :string },
  }
end
  end
end
