###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomGender < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_genders'
    self.hud_key = :PersonalID
    @custom_file_config = HmisCsvTwentyTwentySix.custom_files_config.for('CustomGender.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:PersonalID, 'Client')

    # Validations
    validates :PersonalID, presence: true
    validates :Woman, numericality: { only_integer: true }, allow_blank: true
    validates :Man, numericality: { only_integer: true }, allow_blank: true
    validates :NonBinary, numericality: { only_integer: true }, allow_blank: true
    validates :CulturallySpecific, numericality: { only_integer: true }, allow_blank: true
    validates :Transgender, numericality: { only_integer: true }, allow_blank: true
    validates :Questioning, numericality: { only_integer: true }, allow_blank: true
    validates :DifferentIdentity, numericality: { only_integer: true }, allow_blank: true
    validates :GenderNone, numericality: { only_integer: true }, allow_blank: true
  end
end
