###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomGender < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_genders'
    self.hud_key = :PersonalID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomGender.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:PersonalID, 'Client')

    # Validations
    validates :PersonalID, presence: true
    validates :Woman, numericality: { only_integer: true }, allow_blank: true
    validates :Man, numericality: { only_integer: true }, allow_blank: true
    validates :NonBinary, numericality: { only_integer: true }, allow_blank: true
    validates :CulturallySpecific, numericality: { only_integer: true }, allow_blank: true
    validates :Transgender, numericality: { only_integer: true }, allow_blank: true
    validates :Questioning, numericality: { only_integer: true }, allow_blank: true
    validates :DifferentIdentity, numericality: { only_integer: true }, allow_blank: true
    validates :GenderNone, numericality: { only_integer: true }, allow_blank: true

    def self.hmis_configuration(version: '2026')
      {
        PersonalID: { type: :string, null: false },
        Woman: { type: :integer },
        Man: { type: :integer },
        NonBinary: { type: :integer },
        CulturallySpecific: { type: :integer },
        Transgender: { type: :integer },
        Questioning: { type: :integer },
        DifferentIdentity: { type: :integer },
        GenderNone: { type: :integer },
        DifferentIdentityText: { type: :string },
        DateCreated: { type: :datetime },
        DateUpdated: { type: :datetime },
        UserID: { type: :string },
        DateDeleted: { type: :datetime },
        ExportID: { type: :string },
      }
    end
  end
end
