###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomSexualOrientation < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_sexual_orientations'
    self.hud_key = :EnrollmentID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomSexualOrientation.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:EnrollmentID, 'Enrollment')

    # Validations
    validates :EnrollmentID, presence: true
    validates :SexualOrientation, numericality: { only_integer: true }, allow_blank: true
  end
end
