###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::Custom::FileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Importer::Custom
  class CustomEnrollmentFy26Deprecation < HmisCsvTwentyTwentySix::Importer::Custom::Base
    include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
    self.table_name = 'hmis_2026_custom_enrollment_fy26_deprecations'
    self.hud_key = :EnrollmentID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomEnrollmentFY26Deprecations.csv')

    # Associations
    has_one :destination_record, **hud_assoc(:EnrollmentID, 'Enrollment')

    # Validations
    validates :EnrollmentID, presence: true
    validates :SexualOrientation, numericality: { only_integer: true }, allow_blank: true
    validates :TranslationNeeded, numericality: { only_integer: true }, allow_blank: true
    validates :PreferredLanguage, numericality: { only_integer: true }, allow_blank: true

    def self.hmis_configuration(version: '2026') # rubocop:disable Lint/UnusedMethodArgument
      {
        EnrollmentID: { type: :string, null: false },
        PersonalID: { type: :string },
        SexualOrientation: { type: :integer },
        SexualOrientationOther: { type: :string },
        TranslationNeeded: { type: :integer },
        PreferredLanguage: { type: :integer },
        PreferredLanguageDifferent: { type: :string },
        DateCreated: { type: :datetime },
        DateUpdated: { type: :datetime },
        UserID: { type: :string },
        DateDeleted: { type: :datetime },
        ExportID: { type: :string },
      }
    end
  end
end
