FactoryGirl.define do
  factory :vispdat do
    first_name "MyString"
    nickname "MyString"
    last_name "MyString"
    language 1
    dob "2017-08-09"
    ssn "MyString"
    consent false
    where_sleep 1
    where_sleep_other "MyString"
    where_sleep_refused false
    years_homeless 1
    years_homeless_refused false
    episodes_homeless 1
    episodes_homeless_refused false
    emergency_healthcare 1
    emergency_healthcare_refused false
    ambulance 1
    ambulance_refused false
    inpatient 1
    inpatient_refused false
    crisis_service 1
    crisis_service_refused false
    talked_to_police 1
    talked_to_police_refused false
    jail 1
    jail_refused false
    attacked false
    attacked_refused false
    threatened false
    threatened_refused false
    legal_issue false
    legal_issue_refused false
    tricked false
    tricked_refused false
    risky false
    risky_refused false
    owe_money false
    owe_money_refused false
    receive_money false
    receive_money_refused false
    planned_activities false
    planned_activities_refused false
    basic_needs false
    basic_needs_refused false
    abusive_relationship false
    abusive_relationship_refused false
    leave_due_to_health false
    leave_due_to_health_refused false
    chronic_health false
    chronic_health_refused false
    hiv_program_interest false
    hiv_program_interest_refused false
    physical_disabilities false
    physical_disabilities_refused false
    avoid_help false
    avoid_help_refused false
    pregnant false
    pregnant_refused false
    substance_eviction false
    substance_eviction_refused false
    substance_housing false
    substance_housing_refused false
    housing_mental false
    housing_mental_refused false
    housing_head_injury false
    housing_head_injury_refused false
    housing_learning false
    housing_learning_refused false
    brain_issues false
    brain_issues_refused false
    not_taking_medications false
    not_taking_medications_refused false
    sell_medications false
    sell_medications_refused false
    trauma false
    trauma_refused false
    find_location "MyString"
    find_time "MyString"
    find_period 1
    phone "MyString"
    email "MyString"
    picture false
    picture_refused false
    score 0
  end
end
