AllCops:
  Include:
    # TODO: as these are cleaned, add them back for overcommit
    - '**/Rakefile'
    # - '**/config.ru'
    # - 'lib/tasks/**/*'
    # - 'app/**/*'
    - 'spec/**/*.rb'
    - 'app/controllers/**/*.rb'
    - 'app/inputs/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/jobs/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/mail_interceptors/**/*.rb'
    - 'app/mailers/**/*.rb'
    - 'app/models/**/*.rb'
    # - 'app/models/bi/**/*.rb'
    # - 'app/models/bo/**/*.rb'
    # - 'app/models/cas/**/*.rb'
    # - 'app/models/censuses/**/*.rb'
    # - 'app/models/cohort_columns/**/*.rb'
    # - 'app/models/concerns/**/*.rb'
    # - 'app/models/eto_api/**/*.rb'
    # - 'app/models/exporters/**/*.rb'
    # - 'app/models/filters/**/*.rb'
    # - 'app/models/grda_warehouse/client_notes/**/*.rb'
    # - 'app/models/grda_warehouse/youth/**/*.rb'
    # - 'app/models/grda_warehouse/youth_intake/**/*.rb'
    # - 'app/models/health_emergency/**/*.rb'
    # - 'app/models/performance_dashboards/**/*.rb'
    # - 'app/models/warehouse_report/**/*.rb'
    # - 'app/models/weather/**/*.rb'
    - 'app/renderers/**/*.rb'
    - 'app/uploaders/**/*.rb'
    - 'drivers/**/*.rb'
    - 'lib/**/*.rb'

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'app/assets/**/*'
    - 'bin/db_prep'
    - 'vendor/**/*'

  NewCops: disable

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Max: 175
  Exclude:
    - 'app/models/exporters/tableau'
Metrics/CyclomaticComplexity:
  Max: 50
  Exclude:
    - 'lib/util/hud.rb'
    - 'app/models/exporters/tableau'
Metrics/PerceivedComplexity:
  Max: 50
  Exclude:
    - 'app/models/exporters/tableau'
# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/OptionalBooleanParameter:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

Style/AndOr:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled:
    false

Style/ConditionalAssignment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/RescueStandardError:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# temporarily disabling this due to the number of less-than-3-character-long names in models
Naming/MethodParameterName:
  AllowedNames:
    - c1
    - c2
    - c
    - v
    - k
    - h
    - q
    - qc
    - as
    - id
    - by
    - io
    - to

Style/MixinUsage:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Lint/RescueException:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Style/RegexpLiteral:
  EnforcedStyle: slashes

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/rds_sql_server/hmis_sql_server.rb'

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/RescueEnsureAlignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

# side-step ruby 2.7.2 upgrade issues
Layout/BeginEndAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
