## Call from the caller workflow like so:
# - name: Checkout
#     uses: actions/checkout@v4
# - name: 'Container Setup'
#   id: container-setup
#   uses: ./.github/workflows/container_setup

name: 'Container Setup'
description: 'Sets up the container for running tests'

inputs:
  additional_packages:
    description: 'Additional packages to install'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Add PostgreSQL repository
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
        sudo add-apt-repository -y "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main"
        sudo apt-get update

        # Install packages
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          curl \
          git \
          libpq-dev \
          nodejs \
          npm \
          postgresql-client \
          postgresql-server-dev-17 \
          python3 \
          python3-pip \
          python3-venv \
          unzip \
          ${{ inputs.additional_packages }}
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    - name: Install AWS CLI
      shell: bash
      run: |
        sudo curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        sudo unzip -q awscliv2.zip
        sudo ./aws/install --update
        sudo rm -rf aws awscliv2.zip

    - name: Install Node.js dependencies
      shell: bash
      run: |
        npm install -g yarn

    # - name: Install Python dependencies
    #   shell: bash
    #   run: |
    #     python3 -m pip install --no-cache-dir awscli

    - name: Install Ruby dependencies
      shell: bash
      run: |
        # Fix permissions for Ruby gems
        sudo mkdir -p /var/lib/gems/3.2.0
        sudo chown -R $USER:$USER /var/lib/gems/3.2.0
        sudo chmod -R 755 /var/lib/gems/3.2.0
        gem install bundler
        gem install pg -- --with-pg-config=/usr/bin/pg_config

    # ensure changed-files can read repo files from git
    - name: Configure Git Safe Directory
      shell: ${{ inputs.shell }}
      run: git config --global --add safe.directory /__w/hmis-warehouse/hmis-warehouse

    - name: Set up dependencies
      shell: ${{ inputs.shell }}
      env:
        DATABASE_APP_DB_TEST: warehouse_app_test
        WAREHOUSE_DATABASE_DB_TEST: warehouse_test
        HEALTH_DATABASE_DB_TEST: health_test
        DATABASE_DB_TEST: cas_test
        REPORTING_DATABASE_DB_TEST: reporting_test
        # Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      run: |
        # Add PostgreSQL 17 repository
        sudo apt-get update
        sudo apt-get install -y curl ca-certificates gnupg
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

        # Install NodeJS and Yarn repositories
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/yarn.gpg
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y build-essential imagemagick chromium-browser \
          postgresql-client-16 postgresql-client-17 \
          nodejs yarn freetds-dev libicu-dev libcurl4-openssl-dev \
          libmagic-dev libxml2-dev libxslt1-dev libpq-dev \
          libgeos-dev libheif1 fonts-dejavu fonts-freefont-ttf \
          lftp tmux poppler-utils libyaml-dev libffi-dev

        echo "localhost:5432:*:postgres:postgres" > ~/.pgpass
        chmod 600 ~/.pgpass

    - name: ruby setup
      uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1
      with:
        ruby-version: 3.3
        bundler-cache: true
        working-directory: .

    - name: Install gems
      shell: bash
      run: |
        # Ensure we have write permissions
        sudo mkdir -p /usr/local/bundle
        sudo chown -R $USER:$USER /usr/local/bundle
        sudo chmod -R 755 /usr/local/bundle

        # Install pg gem with correct configuration
        gem install pg -- --with-pg-config=/usr/bin/pg_config
        gem install bundler --version=2.6.3
        bundle config set --local without 'production staging'
        bundle install --jobs 10 --retry 3

    - name: Cache Node.js modules
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Node.js modules
      shell: ${{ inputs.shell }}
      run: yarn install --frozen-lockfile
