## Call from the caller workflow like so:
# - name: Checkout
#     uses: actions/checkout@v4
# - name: 'Container Setup'
#   id: container-setup
#   uses: ./.github/workflows/container_setup

name: "Container Setup"
description: "Reusable action to DRY up CI"
runs:
  using: 'composite'
  steps:
    # ensure changed-files can read repo files from git
    - name: Configure Git Safe Directory
      shell: bash
      run: git config --global --add safe.directory /__w/hmis-warehouse/hmis-warehouse

    - name: Set up dependencies
      shell: bash
      env:
        DATABASE_APP_DB_TEST: warehouse_app_test
        WAREHOUSE_DATABASE_DB_TEST: warehouse_test
        HEALTH_DATABASE_DB_TEST: health_test
        DATABASE_DB_TEST: cas_test
        REPORTING_DATABASE_DB_TEST: reporting_test
        # Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      run: |
        # Add PostgreSQL 17 repository
        sudo apt-get update
        sudo apt-get install -y curl ca-certificates gnupg
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

        # Install NodeJS and Yarn repositories
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/yarn.gpg
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y postgresql-17 postgresql-client-17 postgresql-17-postgis-3 \
          build-essential imagemagick chromium-browser \
          nodejs yarn freetds-dev libicu-dev libcurl4-openssl-dev \
          libmagic-dev libxml2-dev libxslt1-dev libpq-dev \
          libgeos-dev libheif1 fonts-dejavu fonts-freefont-ttf \
          lftp tmux poppler-utils libyaml-dev libffi-dev

        # Install AWS CLI v2
        curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        rm -rf aws awscliv2.zip

        echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
        chmod 600 ~/.pgpass

    - name: ruby setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Cache Node.js modules
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Node.js modules
      shell: bash
      run: yarn install --frozen-lockfile
