class AddMorePublicColors < ActiveRecord::Migration[5.2]
  def change
    add_column :public_report_settings, :gender_color_0, :string
    add_column :public_report_settings, :gender_color_1, :string
    add_column :public_report_settings, :gender_color_2, :string
    add_column :public_report_settings, :gender_color_3, :string
    add_column :public_report_settings, :gender_color_4, :string
    add_column :public_report_settings, :gender_color_5, :string
    add_column :public_report_settings, :gender_color_6, :string
    add_column :public_report_settings, :gender_color_7, :string
    add_column :public_report_settings, :gender_color_8, :string
    add_column :public_report_settings, :age_color_0, :string
    add_column :public_report_settings, :age_color_1, :string
    add_column :public_report_settings, :age_color_2, :string
    add_column :public_report_settings, :age_color_3, :string
    add_column :public_report_settings, :age_color_4, :string
    add_column :public_report_settings, :age_color_5, :string
    add_column :public_report_settings, :age_color_6, :string
    add_column :public_report_settings, :age_color_7, :string
    add_column :public_report_settings, :age_color_8, :string
    add_column :public_report_settings, :household_composition_color_0, :string
    add_column :public_report_settings, :household_composition_color_1, :string
    add_column :public_report_settings, :household_composition_color_2, :string
    add_column :public_report_settings, :household_composition_color_3, :string
    add_column :public_report_settings, :household_composition_color_4, :string
    add_column :public_report_settings, :household_composition_color_5, :string
    add_column :public_report_settings, :household_composition_color_6, :string
    add_column :public_report_settings, :household_composition_color_7, :string
    add_column :public_report_settings, :household_composition_color_8, :string
    add_column :public_report_settings, :race_color_0, :string
    add_column :public_report_settings, :race_color_1, :string
    add_column :public_report_settings, :race_color_2, :string
    add_column :public_report_settings, :race_color_3, :string
    add_column :public_report_settings, :race_color_4, :string
    add_column :public_report_settings, :race_color_5, :string
    add_column :public_report_settings, :race_color_6, :string
    add_column :public_report_settings, :race_color_7, :string
    add_column :public_report_settings, :race_color_8, :string
    add_column :public_report_settings, :time_color_0, :string
    add_column :public_report_settings, :time_color_1, :string
    add_column :public_report_settings, :time_color_2, :string
    add_column :public_report_settings, :time_color_3, :string
    add_column :public_report_settings, :time_color_4, :string
    add_column :public_report_settings, :time_color_5, :string
    add_column :public_report_settings, :time_color_6, :string
    add_column :public_report_settings, :time_color_7, :string
    add_column :public_report_settings, :time_color_8, :string
    add_column :public_report_settings, :housing_type_color_0, :string
    add_column :public_report_settings, :housing_type_color_1, :string
    add_column :public_report_settings, :housing_type_color_2, :string
    add_column :public_report_settings, :housing_type_color_3, :string
    add_column :public_report_settings, :housing_type_color_4, :string
    add_column :public_report_settings, :housing_type_color_5, :string
    add_column :public_report_settings, :housing_type_color_6, :string
    add_column :public_report_settings, :housing_type_color_7, :string
    add_column :public_report_settings, :housing_type_color_8, :string
    add_column :public_report_settings, :population_color_0, :string
    add_column :public_report_settings, :population_color_1, :string
    add_column :public_report_settings, :population_color_2, :string
    add_column :public_report_settings, :population_color_3, :string
    add_column :public_report_settings, :population_color_4, :string
    add_column :public_report_settings, :population_color_5, :string
    add_column :public_report_settings, :population_color_6, :string
    add_column :public_report_settings, :population_color_7, :string
    add_column :public_report_settings, :population_color_8, :string
  end
end
