###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Exporter::Custom
  class CustomDataElementDefinition < Base
    def self.custom_file_name
      'CustomDataElementDefinition.csv'
    end

    def self.export_scope(**_options)
      # No export class specified
      []
    end

    def self.transforms
      [
        HmisCsvTwentyTwentySix::Exporter::Custom::CustomDataElementDefinition,
      ]
    end
  end
end
