###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Exporter::Custom
  class CustomDataElement < Base
    def self.custom_file_name
      'CustomDataElement.csv'
    end

    def self.export_scope(**options)
      export_scope_with_owner_filtering(**options)
    end

    def self.transforms
      [
        HmisCsvTwentyTwentySix::Exporter::Custom::CustomDataElement,
      ]
    end

    def self.adjust_keys(row, _export)
      row.UserID = row.user_id || 'op-system'
      row[:CustomDataElementID] = row.id

      # Map warehouse column values to export column values
      apply_warehouse_to_export_mappings(row)
    end

    def self.owner_class_mapping
      {
        'Client' => 'GrdaWarehouse::Hud::Client',
        'Enrollment' => 'GrdaWarehouse::Hud::Enrollment',
        'Project' => 'GrdaWarehouse::Hud::Project',
        'Organization' => 'GrdaWarehouse::Hud::Organization',
      }
    end

    def self.warehouse_class_for_export
      GrdaWarehouse::Hud::CustomDataElement
    end
  end
end
