###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Exporter::Custom
  class CustomGender < Base
    def self.custom_file_name
      'CustomGender.csv'
    end

    def self.export_scope(**options)
      # Use the same export scope as the standard Client exporter
      HmisCsvTwentyTwentySix::Exporter::Client.export_scope(**options)
    end

    def self.transforms
      [
        HmisCsvTwentyTwentySix::Exporter::Custom::CustomGender,
      ]
    end

    def self.adjust_keys(row, export)
      # Delegate to the standard exporter's adjust_keys method
      HmisCsvTwentyTwentySix::Exporter::Client.adjust_keys(row, export)
    end
  end
end
