---
title: Admin Assign Workflow
---
flowchart TD
start_referral_1975(("Start Referral<br/><br/>EFFECT: Start Workflow → Start Referral"))
start_referral_1975--> admin_assign_1976
admin_assign_1976("Admin Assign<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
admin_assign_1976--> create_ce_event_1977
create_ce_event_1977("Create CE Event (script)<br/><br/>EFFECT: Complete Step → Create Ce Event")
create_ce_event_1977--> provider_outcome_1978
provider_outcome_1978("Provider Outcome<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_1978--> exclusive_gateway_provider_outcome_1_1991
exclusive_gateway_provider_outcome_1_1991{"Exclusive Gateway: provider_outcome_1"}
exclusive_gateway_provider_outcome_1_1991-- IF move_forward = 0 --> denial_review_1981
exclusive_gateway_provider_outcome_1_1991--> create_enrollment_1987
denial_review_1981("Denial Review<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
denial_review_1981--> exclusive_gateway_denial_review_1_1994
exclusive_gateway_denial_review_1_1994{"Exclusive Gateway: denial_review_1"}
exclusive_gateway_denial_review_1_1994-- IF denial_review_decision = 1 --> exclusive_gateway_admin_decline_gateway_1990
exclusive_gateway_denial_review_1_1994--> provider_outcome_second_attempt_1979
exclusive_gateway_admin_decline_gateway_1990{"Exclusive Gateway: admin_decline_gateway"}
exclusive_gateway_denial_review_2_1995-- IF denial_review_decision = 1 --> exclusive_gateway_admin_decline_gateway_1990
denial_review_third_1983--> exclusive_gateway_admin_decline_gateway_1990
confirm_success_1984-- IF move_forward = 0 --> exclusive_gateway_admin_decline_gateway_1990
exclusive_gateway_admin_decline_gateway_1990-- IF referral_result = 2 --> update_ce_event_with_result_unsuccessful_referral_client_rejected_1986
exclusive_gateway_admin_decline_gateway_1990-- IF referral_result = 3 --> update_ce_event_with_result_unsuccessful_referral_provider_rejected_1985
exclusive_gateway_admin_decline_gateway_1990--> referral_declined_1989
update_ce_event_with_result_unsuccessful_referral_client_rejected_1986("Update CE Event with result 'Unsuccessful referral: client rejected' (script)<br/><br/>EFFECT: Complete Step → Set Ce Event Result<br/>PARAMS: referral_result: 2")
update_ce_event_with_result_unsuccessful_referral_client_rejected_1986--> referral_declined_1989
referral_declined_1989(("Referral Declined<br/><br/>EFFECT: End Workflow → Reject Referral"))
update_ce_event_with_result_unsuccessful_referral_provider_rejected_1985--> referral_declined_1989
update_ce_event_with_result_unsuccessful_referral_provider_rejected_1985("Update CE Event with result 'Unsuccessful referral: provider rejected' (script)<br/><br/>EFFECT: Complete Step → Set Ce Event Result<br/>PARAMS: referral_result: 3")
provider_outcome_second_attempt_1979("Provider Outcome (Second Attempt)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_second_attempt_1979--> exclusive_gateway_provider_outcome_2_1992
exclusive_gateway_provider_outcome_2_1992{"Exclusive Gateway: provider_outcome_2"}
exclusive_gateway_provider_outcome_2_1992-- IF move_forward = 0 --> denial_review_second_1982
exclusive_gateway_provider_outcome_2_1992--> create_enrollment_1987
denial_review_second_1982("Denial Review (Second)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
denial_review_second_1982--> exclusive_gateway_denial_review_2_1995
exclusive_gateway_denial_review_2_1995{"Exclusive Gateway: denial_review_2"}
exclusive_gateway_denial_review_2_1995--> provider_outcome_third_attempt_1980
provider_outcome_third_attempt_1980("Provider Outcome (Third Attempt)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_third_attempt_1980--> exclusive_gateway_provider_outcome_3_1993
exclusive_gateway_provider_outcome_3_1993{"Exclusive Gateway: provider_outcome_3"}
exclusive_gateway_provider_outcome_3_1993-- IF move_forward = 0 --> denial_review_third_1983
exclusive_gateway_provider_outcome_3_1993--> create_enrollment_1987
denial_review_third_1983("Denial Review (Third)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
create_enrollment_1987("Create Enrollment (script)<br/><br/>EFFECT: Complete Step → Create Enrollment")
create_enrollment_1987--> confirm_success_1984
confirm_success_1984("Confirm Success")
confirm_success_1984-- IF move_forward = 1 --> referral_accepted_1988
referral_accepted_1988(("Referral Accepted<br/><br/>EFFECT: End Workflow → Accept Referral<br/>---<br/>EFFECT: End Workflow → Set Ce Event Result<br/>PARAMS: referral_result: 1"))