---
title: Housing Referral Workflow V1
---
flowchart TD
start_referral_1996(("Start Referral<br/><br/>EFFECT: Start Workflow → Start Referral"))
start_referral_1996--> initial_review_1997
initial_review_1997("Initial Review<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: matching_in_progress")
initial_review_1997--> exclusive_gateway_initial_review_task_2019
exclusive_gateway_initial_review_task_2019{"Exclusive Gateway: initial_review_task"}
exclusive_gateway_initial_review_task_2019-- IF move_forward = 0 --> exclusive_gateway_admin_decline_gateway_2013
exclusive_gateway_initial_review_task_2019--> initial_client_engagement_1998
exclusive_gateway_admin_decline_gateway_2013{"Exclusive Gateway: admin_decline_gateway"}
exclusive_gateway_denial_review_1_2017-- IF denial_review_decision = 1 --> exclusive_gateway_admin_decline_gateway_2013
exclusive_gateway_denial_review_2_2018-- IF denial_review_decision = 1 --> exclusive_gateway_admin_decline_gateway_2013
denial_review_third_2006--> exclusive_gateway_admin_decline_gateway_2013
confirm_success_2007-- IF move_forward = 0 --> exclusive_gateway_admin_decline_gateway_2013
exclusive_gateway_client_engagement_task_2020-- IF move_forward = 0 --> exclusive_gateway_admin_decline_gateway_2013
exclusive_gateway_client_offer_outcome_2021-- IF move_forward = 0 --> exclusive_gateway_admin_decline_gateway_2013
exclusive_gateway_admin_decline_gateway_2013-- IF referral_result = 2 --> update_ce_event_with_result_unsuccessful_referral_client_rejected_2009
exclusive_gateway_admin_decline_gateway_2013-- IF referral_result = 3 --> update_ce_event_with_result_unsuccessful_referral_provider_rejected_2008
exclusive_gateway_admin_decline_gateway_2013--> referral_declined_2012
update_ce_event_with_result_unsuccessful_referral_client_rejected_2009("Update CE Event with result 'Unsuccessful referral: client rejected' (script)<br/><br/>EFFECT: Complete Step → Set Ce Event Result<br/>PARAMS: referral_result: 2")
update_ce_event_with_result_unsuccessful_referral_client_rejected_2009--> referral_declined_2012
referral_declined_2012(("Referral Declined<br/><br/>EFFECT: End Workflow → Reject Referral"))
update_ce_event_with_result_unsuccessful_referral_provider_rejected_2008--> referral_declined_2012
update_ce_event_with_result_unsuccessful_referral_provider_rejected_2008("Update CE Event with result 'Unsuccessful referral: provider rejected' (script)<br/><br/>EFFECT: Complete Step → Set Ce Event Result<br/>PARAMS: referral_result: 3")
initial_client_engagement_1998("Initial Client Engagement")
initial_client_engagement_1998--> client_engagement_1999
client_engagement_1999("Client Engagement")
client_engagement_1999--> exclusive_gateway_client_engagement_task_2020
exclusive_gateway_client_engagement_task_2020{"Exclusive Gateway: client_engagement_task"}
exclusive_gateway_client_engagement_task_2020--> client_offer_outcome_2000
client_offer_outcome_2000("Client Offer Outcome<br/><br/>EFFECT: Enable Step → Create Ce Event")
client_offer_outcome_2000--> exclusive_gateway_client_offer_outcome_2021
exclusive_gateway_client_offer_outcome_2021{"Exclusive Gateway: client_offer_outcome"}
exclusive_gateway_client_offer_outcome_2021--> provider_outcome_2001
provider_outcome_2001("Provider Outcome<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_2001--> exclusive_gateway_provider_outcome_1_2014
exclusive_gateway_provider_outcome_1_2014{"Exclusive Gateway: provider_outcome_1"}
exclusive_gateway_provider_outcome_1_2014-- IF move_forward = 0 --> denial_review_2004
exclusive_gateway_provider_outcome_1_2014--> create_enrollment_2010
denial_review_2004("Denial Review<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
denial_review_2004--> exclusive_gateway_denial_review_1_2017
exclusive_gateway_denial_review_1_2017{"Exclusive Gateway: denial_review_1"}
exclusive_gateway_denial_review_1_2017--> provider_outcome_second_attempt_2002
provider_outcome_second_attempt_2002("Provider Outcome (Second Attempt)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_second_attempt_2002--> exclusive_gateway_provider_outcome_2_2015
exclusive_gateway_provider_outcome_2_2015{"Exclusive Gateway: provider_outcome_2"}
exclusive_gateway_provider_outcome_2_2015-- IF move_forward = 0 --> denial_review_second_2005
exclusive_gateway_provider_outcome_2_2015--> create_enrollment_2010
denial_review_second_2005("Denial Review (Second)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
denial_review_second_2005--> exclusive_gateway_denial_review_2_2018
exclusive_gateway_denial_review_2_2018{"Exclusive Gateway: denial_review_2"}
exclusive_gateway_denial_review_2_2018--> provider_outcome_third_attempt_2003
provider_outcome_third_attempt_2003("Provider Outcome (Third Attempt)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: assigned")
provider_outcome_third_attempt_2003--> exclusive_gateway_provider_outcome_3_2016
exclusive_gateway_provider_outcome_3_2016{"Exclusive Gateway: provider_outcome_3"}
exclusive_gateway_provider_outcome_3_2016-- IF move_forward = 0 --> denial_review_third_2006
exclusive_gateway_provider_outcome_3_2016--> create_enrollment_2010
denial_review_third_2006("Denial Review (Third)<br/><br/>EFFECT: Enable Step → Set Custom Referral Status<br/>PARAMS: custom_status_key: denial_pending")
create_enrollment_2010("Create Enrollment (script)<br/><br/>EFFECT: Complete Step → Create Enrollment")
create_enrollment_2010--> confirm_success_2007
confirm_success_2007("Confirm Success")
confirm_success_2007-- IF move_forward = 1 --> referral_accepted_2011
referral_accepted_2011(("Referral Accepted<br/><br/>EFFECT: End Workflow → Accept Referral<br/>---<br/>EFFECT: End Workflow → Set Ce Event Result<br/>PARAMS: referral_result: 1"))