class ClaimsReportingMedicalClaim < ActiveRecord::Migration[5.2]
  def change
    create_table :claims_reporting_medical_claims do |t|
      t.column 'member_id', 'string', limit: 50
      t.column 'claim_number', 'string', limit: 30
      t.column 'line_number', 'string', limit: 10
      t.column 'cp_pidsl', 'string', limit: 50
      t.column 'cp_name', 'string', limit: 255
      t.column 'aco_pidsl', 'string', limit: 50
      t.column 'aco_name', 'string', limit: 255
      t.column 'pcc_pidsl', 'string', limit: 50
      t.column 'pcc_name', 'string', limit: 255
      t.column 'pcc_npi', 'string', limit: 50
      t.column 'pcc_taxid', 'string', limit: 50
      t.column 'mco_pidsl', 'string', limit: 50
      t.column 'mco_name', 'string', limit: 50
      t.column 'source', 'string', limit: 50
      t.column 'claim_type', 'string', limit: 255
      t.column 'member_dob', 'date', limit: nil
      t.column 'patient_status', 'string', limit: 255
      t.column 'service_start_date', 'date', limit: nil
      t.column 'service_end_date', 'date', limit: nil
      t.column 'admit_date', 'date', limit: nil
      t.column 'discharge_date', 'date', limit: nil
      t.column 'type_of_bill', 'string', limit: 255
      t.column 'admit_source', 'string', limit: 255
      t.column 'admit_type', 'string', limit: 255
      t.column 'frequency_code', 'string', limit: 255
      t.column 'paid_date', 'date', limit: nil
      t.column 'billed_amount', 'decimal(19,4)', limit: nil
      t.column 'allowed_amount', 'decimal(19,4)', limit: nil
      t.column 'paid_amount', 'decimal(19,4)', limit: nil
      t.column 'admit_diagnosis', 'string', limit: 50
      t.column 'dx_1', 'string', limit: 50
      t.column 'dx_2', 'string', limit: 50
      t.column 'dx_3', 'string', limit: 50
      t.column 'dx_4', 'string', limit: 50
      t.column 'dx_5', 'string', limit: 50
      t.column 'dx_6', 'string', limit: 50
      t.column 'dx_7', 'string', limit: 50
      t.column 'dx_8', 'string', limit: 50
      t.column 'dx_9', 'string', limit: 50
      t.column 'dx_10', 'string', limit: 50
      t.column 'dx_11', 'string', limit: 50
      t.column 'dx_12', 'string', limit: 50
      t.column 'dx_13', 'string', limit: 50
      t.column 'dx_14', 'string', limit: 50
      t.column 'dx_15', 'string', limit: 50
      t.column 'dx_16', 'string', limit: 50
      t.column 'dx_17', 'string', limit: 50
      t.column 'dx_18', 'string', limit: 50
      t.column 'dx_19', 'string', limit: 50
      t.column 'dx_20', 'string', limit: 50
      t.column 'dx_21', 'string', limit: 50
      t.column 'dx_22', 'string', limit: 50
      t.column 'dx_23', 'string', limit: 50
      t.column 'dx_24', 'string', limit: 50
      t.column 'dx_25', 'string', limit: 50
      t.column 'e_dx_1', 'string', limit: 50
      t.column 'e_dx_2', 'string', limit: 50
      t.column 'e_dx_3', 'string', limit: 50
      t.column 'e_dx_4', 'string', limit: 50
      t.column 'e_dx_5', 'string', limit: 50
      t.column 'e_dx_6', 'string', limit: 50
      t.column 'e_dx_7', 'string', limit: 50
      t.column 'e_dx_8', 'string', limit: 50
      t.column 'e_dx_9', 'string', limit: 50
      t.column 'e_dx_10', 'string', limit: 50
      t.column 'e_dx_11', 'string', limit: 50
      t.column 'e_dx_12', 'string', limit: 50
      t.column 'icd_version', 'string', limit: 50
      t.column 'surgical_procedure_code_1', 'string', limit: 50
      t.column 'surgical_procedure_code_2', 'string', limit: 50
      t.column 'surgical_procedure_code_3', 'string', limit: 50
      t.column 'surgical_procedure_code_4', 'string', limit: 50
      t.column 'surgical_procedure_code_5', 'string', limit: 50
      t.column 'surgical_procedure_code_6', 'string', limit: 50
      t.column 'revenue_code', 'string', limit: 50
      t.column 'place_of_service_code', 'string', limit: 50
      t.column 'procedure_code', 'string', limit: 50
      t.column 'procedure_modifier_1', 'string', limit: 50
      t.column 'procedure_modifier_2', 'string', limit: 50
      t.column 'procedure_modifier_3', 'string', limit: 50
      t.column 'procedure_modifier_4', 'string', limit: 50
      t.column 'drg_code', 'string', limit: 50
      t.column 'drg_version_code', 'string', limit: 50
      t.column 'severity_of_illness', 'string', limit: 50
      t.column 'service_provider_npi', 'string', limit: 50
      t.column 'id_provider_servicing', 'string', limit: 50
      t.column 'servicing_taxid', 'string', limit: 50
      t.column 'servicing_provider_name', 'string', limit: 512
      t.column 'servicing_provider_type', 'string', limit: 255
      t.column 'servicing_provider_taxonomy', 'string', limit: 255
      t.column 'servicing_address', 'string', limit: 512
      t.column 'servicing_city', 'string', limit: 255
      t.column 'servicing_state', 'string', limit: 255
      t.column 'servicing_zip', 'string', limit: 50
      t.column 'billing_npi', 'string', limit: 50
      t.column 'id_provider_billing', 'string', limit: 50
      t.column 'billing_taxid', 'string', limit: 50
      t.column 'billing_provider_name', 'string', limit: 512
      t.column 'billing_provider_type', 'string', limit: 50
      t.column 'billing_provider_taxonomy', 'string', limit: 50
      t.column 'billing_address', 'string', limit: 512
      t.column 'billing_city', 'string', limit: 255
      t.column 'billing_state', 'string', limit: 255
      t.column 'billing_zip', 'string', limit: 50
      t.column 'claim_status', 'string', limit: 255
      t.column 'disbursement_code', 'string', limit: 255
      t.column 'enrolled_flag', 'string', limit: 50
      t.column 'referral_circle_ind', 'string', limit: 50
      t.column 'mbhp_flag', 'string', limit: 50
      t.column 'present_on_admission_1', 'string', limit: 50
      t.column 'present_on_admission_2', 'string', limit: 50
      t.column 'present_on_admission_3', 'string', limit: 50
      t.column 'present_on_admission_4', 'string', limit: 50
      t.column 'present_on_admission_5', 'string', limit: 50
      t.column 'present_on_admission_6', 'string', limit: 50
      t.column 'present_on_admission_7', 'string', limit: 50
      t.column 'present_on_admission_8', 'string', limit: 50
      t.column 'present_on_admission_9', 'string', limit: 50
      t.column 'present_on_admission_10', 'string', limit: 50
      t.column 'present_on_admission_11', 'string', limit: 50
      t.column 'present_on_admission_12', 'string', limit: 50
      t.column 'present_on_admission_13', 'string', limit: 50
      t.column 'present_on_admission_14', 'string', limit: 50
      t.column 'present_on_admission_15', 'string', limit: 50
      t.column 'present_on_admission_16', 'string', limit: 50
      t.column 'present_on_admission_17', 'string', limit: 50
      t.column 'present_on_admission_18', 'string', limit: 50
      t.column 'present_on_admission_19', 'string', limit: 50
      t.column 'present_on_admission_20', 'string', limit: 50
      t.column 'present_on_admission_21', 'string', limit: 50
      t.column 'present_on_admission_22', 'string', limit: 50
      t.column 'present_on_admission_23', 'string', limit: 50
      t.column 'present_on_admission_24', 'string', limit: 50
      t.column 'present_on_admission_25', 'string', limit: 50
      t.column 'e_dx_present_on_admission_1', 'string', limit: 50
      t.column 'e_dx_present_on_admission_2', 'string', limit: 50
      t.column 'e_dx_present_on_admission_3', 'string', limit: 50
      t.column 'e_dx_present_on_admission_4', 'string', limit: 50
      t.column 'e_dx_present_on_admission_5', 'string', limit: 50
      t.column 'e_dx_present_on_admission_6', 'string', limit: 50
      t.column 'e_dx_present_on_admission_7', 'string', limit: 50
      t.column 'e_dx_present_on_admission_8', 'string', limit: 50
      t.column 'e_dx_present_on_admission_9', 'string', limit: 50
      t.column 'e_dx_present_on_admission_10', 'string', limit: 50
      t.column 'e_dx_present_on_admission_11', 'string', limit: 50
      t.column 'e_dx_present_on_admission_12', 'string', limit: 50
      t.column 'quantity', 'decimal(12,4)', limit: nil
      t.column 'price_method', 'string', limit: 50
    end
  end
end
