###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

module HmisCsvTwentyTwentySix
  # Manages dynamic generation of custom file models based on YAML configuration
  #
  # This class reads individual YAML files from drivers/hmis_csv_twenty_twenty_six/config/custom/
  # and generates corresponding migrations and model files.
  #
  # @example YAML Configuration Structure
  #   # custom_gender.yaml
  #   custom_files:
  #     - filename: "CustomGender.csv"
  #       class_name: "CustomGender"
  #       required: false
  #       description: "Gender identity data in FY2024 format"
  #       augments_warehouse_table: "GrdaWarehouse::Hud::Client"
  #       augment_key: "PersonalID"
  #       columns:
  #         - name: "PersonalID"
  #           type: "string"
  #           required: true
  #           validations: ["NonBlank"]
  #         - name: "Woman"
  #           type: "integer"
  #           warehouse_column_mapping:
  #             type: "direct"
  #             target_column: "Woman"
  #
  # @example Usage
  #   # Generate all custom models and migrations
  #   HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models!
  #
  class CustomFileManager
    # Generates all custom models and migrations based on YAML configuration files
    #
    # Reads all .yaml files from the custom config directory and creates:
    # - Migration files for any tables that don't exist
    # - Loader model files
    # - Importer model files
    #
    # @return [void]
    def self.bootstrap_custom_models!
      HmisCsvTwentyTwentySix.custom_files_config.definitions.each do |definition|
        generate_migration_for_file(definition)
        generate_loader_model_file(definition)
        generate_importer_model_file(definition)
      end
    end

    # Creates a Loader model file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_loader_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/#{definition.class_name.underscore}.rb")
      table_name = "hmis_csv_2026_#{definition.class_name.underscore.pluralize}"

      content = ::Code.copywright_header
      content += <<~RUBY
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED. DO NOT EDIT.
        # Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

        module HmisCsvTwentyTwentySix::Loader::Custom
          class #{definition.class_name} < HmisCsvTwentyTwentySix::Loader::Custom::Base
            self.table_name = '#{table_name}'
            self.hud_key = :#{definition.hud_key}
            @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('#{definition.filename}')
          end
        end
      RUBY

      File.write(file_path, content)
    end

    # Creates an Importer model file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_importer_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/#{definition.class_name.underscore}.rb")
      table_name = "hmis_2026_#{definition.class_name.underscore.pluralize}"
      associations_code = generate_associations_code(definition)
      validations_code = generate_validations_code(definition)

      content = ::Code.copywright_header
      content += <<~RUBY
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED. DO NOT EDIT.
        # Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

        module HmisCsvTwentyTwentySix::Importer::Custom
          class #{definition.class_name} < HmisCsvTwentyTwentySix::Importer::Custom::Base
            include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
            self.table_name = '#{table_name}'
            self.hud_key = :#{definition.hud_key}
            @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('#{definition.filename}')

            # Associations
            #{associations_code}

            # Validations
            #{validations_code}
          end
        end
      RUBY

      File.write(file_path, content)
    end

    private_class_method def self.generate_associations_code(definition)
      return unless definition.warehouse_class

      model_name = definition.warehouse_class.name.split('::').last
      "has_one :destination_record, **hud_assoc(:#{definition.hud_key}, '#{model_name}')"
    end

    private_class_method def self.generate_validations_code(definition)
      definition.columns.map do |column_config|
        column_name = column_config['name']
        validations = []

        validations << "validates :#{column_name}, presence: true" if column_config['required']
        validations << "validates :#{column_name}, length: { maximum: #{column_config['max_length']} }" if column_config['max_length']

        case column_config['type']
        when 'integer'
          validations << "validates :#{column_name}, numericality: { only_integer: true }, allow_blank: true"
        when 'boolean'
          validations << "validates :#{column_name}, inclusion: { in: [true, false, 0, 1, '0', '1', 'true', 'false'] }, allow_blank: true"
        end

        if column_config['validations']
          column_config['validations'].each do |validation|
            if validation.is_a?(String)
              # Handle string format validations
              if validation == 'NonBlank' && !column_config['required']
                validations << "validates :#{column_name}, presence: true"
              elsif validation.start_with?('inclusion:', 'length:', 'numericality:')
                # Handle inline validation strings like "inclusion: { in: %w[Client Enrollment] }"
                validations << "validates :#{column_name}, #{validation}"
              end
            elsif validation.is_a?(Hash)
              validation_class = validation['class']
              arguments = validation['arguments'] || {}
              validations << "validates :#{column_name}, #{validation_class.underscore}: { in: #{arguments['valid_options']} }" if validation_class == 'InclusionInSet'
            end
          end
        end

        validations
      end.flatten.uniq.join("\n    ")
    end

    # Generates a migration file for a specific custom file if tables don't exist
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_migration_for_file(definition)
      loader_table = "hmis_csv_2026_#{definition.class_name.underscore.pluralize}"
      importer_table = "hmis_2026_#{definition.class_name.underscore.pluralize}"

      # Check if tables exist
      loader_exists = GrdaWarehouseBase.connection.table_exists?(loader_table)
      importer_exists = GrdaWarehouseBase.connection.table_exists?(importer_table)

      return if loader_exists && importer_exists

      # Generate migration
      timestamp = Time.current.strftime('%Y%m%d%H%M%S')
      migration_name = "create_#{definition.class_name.underscore}_custom_tables"
      migration_file = "db/warehouse/migrate/#{timestamp}_#{migration_name}.rb"

      migration_content = generate_migration_content(
        definition: definition,
        loader_table: loader_table,
        importer_table: importer_table,
        loader_exists: loader_exists,
        importer_exists: importer_exists,
        migration_name: migration_name,
      )

      File.write(Rails.root.join(migration_file), migration_content)
      puts "Generated migration: #{migration_file}"
    end

    # Generates the content for a migration file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param loader_table [String] Name of the loader table
    # @param importer_table [String] Name of the importer table
    # @param loader_exists [Boolean] Whether loader table exists
    # @param importer_exists [Boolean] Whether importer table exists
    # @param migration_name [String] Name of the migration class
    # @return [String] Migration file content
    # @private
    private_class_method def self.generate_migration_content(definition:, loader_table:, importer_table:, loader_exists:, importer_exists:, migration_name:)
      class_name = migration_name.camelize

      content = <<~MIGRATION
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED.
        class #{class_name} < ActiveRecord::Migration[7.1]
          def change
        #{generate_loader_table_migration(definition, loader_table) unless loader_exists}
        #{generate_importer_table_migration(definition, importer_table) unless importer_exists}
            # End generated migration content
          end
        end
      MIGRATION

      content
    end

    # Generates loader table creation code
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param table_name [String] Name of the loader table
    # @return [String] Migration code for loader table
    # @private
    private_class_method def self.generate_loader_table_migration(definition, table_name)
      columns = definition.real_columns.map do |col|
        "      t.string '#{col['name']}'"
      end.join("\n")

      # Use first real column for index (virtual columns shouldn't be used for indexing)
      first_column = definition.real_columns.first['name']

      <<~LOADER_TABLE
            # #{definition.class_name} loader table
            create_table :#{table_name} do |t|
        #{columns}

              # Standard loader columns
              t.references :data_source, null: false, index: true
              t.datetime :loaded_at, null: false
              t.references :loader, null: false, index: true
            end

            # Add indexes for loader table
            add_index :#{table_name}, [:#{first_column}, :data_source_id], name: 'idx_#{table_name.gsub('hmis_csv_2026_', '')}_id_ds'
      LOADER_TABLE
    end

    # Generates importer table creation code
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param table_name [String] Name of the importer table
    # @return [String] Migration code for importer table
    # @private
    private_class_method def self.generate_importer_table_migration(definition, table_name)
      columns = definition.real_columns.map do |col|
        column_type = case col['type']
        when 'integer' then 'integer'
        when 'datetime', 'date' then 'datetime'
        when 'boolean' then 'boolean'
        else 'string'
        end
        "      t.#{column_type} '#{col['name']}'"
      end.join("\n")

      # Use first real column for index (virtual columns shouldn't be used for indexing)
      first_column = definition.real_columns.first['name']

      <<~IMPORTER_TABLE
            # #{definition.class_name} importer table
            create_table :#{table_name} do |t|
        #{columns}

              # Standard importer columns
              t.references :data_source, null: false, index: true
              t.references :importer_log, null: false, index: true
              t.datetime :pre_processed_at, null: false
              t.string :source_hash
              t.references :source, null: false, index: false
              t.string :source_type, null: false
              t.timestamp :dirty_at
              t.timestamp :clean_at
              t.boolean :should_import, default: true
            end

            # Add indexes for importer table
            add_index :#{table_name}, [:#{first_column}, :data_source_id], name: 'idx_#{table_name.gsub('hmis_2026_', '')}_imp_id_ds'
            add_index :#{table_name}, [:source_type, :source_id], name: 'idx_#{table_name.gsub('hmis_2026_', '')}_source'
      IMPORTER_TABLE
    end

    # Removes all custom model files generated by bootstrap_custom_models!
    #
    # This method removes:
    # - Loader model files from drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/
    # - Importer model files from drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/
    #
    # Note: This does NOT remove migration files or drop database tables.
    # You'll need to handle those separately if needed.  This is a convenience method for development.
    #
    # @return [void]
    def self.clean_custom_models!
      HmisCsvTwentyTwentySix.custom_files_config.definitions.each do |definition|
        remove_loader_model_file(definition)
        remove_importer_model_file(definition)
      end
    end

    private_class_method def self.remove_loader_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/#{definition.class_name.underscore}.rb")

      if File.exist?(file_path)
        File.delete(file_path)
        puts "Removed loader model: #{file_path}"
      else
        puts "Loader model not found: #{file_path}"
      end
    end

    private_class_method def self.remove_importer_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/#{definition.class_name.underscore}.rb")

      if File.exist?(file_path)
        File.delete(file_path)
        puts "Removed importer model: #{file_path}"
      else
        puts "Importer model not found: #{file_path}"
      end
    end
  end
end
