###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

module HmisCsvTwentyTwentySix
  # Manages dynamic generation of custom file models based on YAML configuration
  #
  # This class reads individual YAML files from drivers/hmis_csv_twenty_twenty_six/config/custom/
  # and generates corresponding migrations and model files.
  #
  # @example YAML Configuration Structure
  #   # custom_gender.yaml
  #   custom_files:
  #     - filename: "CustomGender.csv"
  #       class_name: "CustomGender"
  #       required: false
  #       description: "Gender identity data in FY2024 format"
  #       augments_warehouse_table: "GrdaWarehouse::Hud::Client"
  #       augment_key: "PersonalID"
  #       columns:
  #         - name: "PersonalID"
  #           type: "string"
  #           required: true
  #           validations: ["NonBlank"]
  #         - name: "Woman"
  #           type: "integer"
  #           warehouse_column_mapping:
  #             type: "direct"
  #             target_column: "Woman"
  #
  # @example Usage
  #   # Generate all custom models and migrations
  #   HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models!
  #
  class CustomFileManager
    # Generates all custom models and migrations based on YAML configuration files
    #
    # Reads all .yaml files from the custom config directory and creates:
    # - Migration files for any tables that don't exist
    # - Loader model files
    # - Importer model files
    #
    # @return [void]
    def self.bootstrap_custom_models!
      HmisCsvTwentyTwentySix.custom_files_config.definitions.each do |definition|
        generate_migration_for_file(definition)
        generate_loader_model_file(definition)
        generate_importer_model_file(definition)
        generate_exporter_model_file(definition)
      end
    end

    # Creates a Loader model file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_loader_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/#{definition.class_name.underscore}.rb")
      table_name = "hmis_csv_2026_#{definition.class_name.underscore.pluralize}"

      content = ::Code.copywright_header
      content += <<~RUBY
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED. DO NOT EDIT.
        # Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

        module HmisCsvTwentyTwentySix::Loader::Custom
          class #{definition.class_name} < HmisCsvTwentyTwentySix::Loader::Custom::Base
            self.table_name = '#{table_name}'
            self.hud_key = :#{definition.hud_key}
            @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('#{definition.filename}')
          end
        end
      RUBY

      File.write(file_path, content)
    end

    # Creates an Importer model file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_importer_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/#{definition.class_name.underscore}.rb")
      table_name = "hmis_2026_#{definition.class_name.underscore.pluralize}"
      associations_code = generate_associations_code(definition)
      validations_code = generate_validations_code(definition)
      hmis_configuration_code = generate_hmis_configuration_code(definition)

      content = ::Code.copywright_header
      content += <<~RUBY
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED. DO NOT EDIT.
        # Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

        module HmisCsvTwentyTwentySix::Importer::Custom
          class #{definition.class_name} < HmisCsvTwentyTwentySix::Importer::Custom::Base
            include HmisCsvTwentyTwentySix::Importer::Custom::CustomImportConcern
            self.table_name = '#{table_name}'
            self.hud_key = :#{definition.hud_key}
            @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('#{definition.filename}')

            # Associations
            #{associations_code}

            # Validations
            #{validations_code}

            #{hmis_configuration_code}
          end
        end
      RUBY

      File.write(file_path, content)
    end

    # Creates an Exporter model file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_exporter_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/exporter/custom/#{definition.class_name.underscore}.rb")
      export_scope_code = generate_export_scope_code(definition)
      adjust_keys_code = generate_adjust_keys_code(definition)

      content = ::Code.copywright_header
      content += <<~RUBY
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED. DO NOT EDIT.
        # Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

        module HmisCsvTwentyTwentySix::Exporter::Custom
          class #{definition.class_name} < Base
            def self.custom_file_name
              '#{definition.filename}'
            end

            def self.export_scope(**options)
              #{export_scope_code}
            end

            def self.transforms
              [
                HmisCsvTwentyTwentySix::Exporter::Custom::#{definition.class_name},
              ]
            end#{adjust_keys_code.present? ? "\n\n    #{adjust_keys_code}" : ''}
          end
        end
      RUBY

      # Ensure directory exists
      FileUtils.mkdir_p(File.dirname(file_path))
      File.write(file_path, content)
    end

    private_class_method def self.generate_associations_code(definition)
      return unless definition.warehouse_class

      model_name = definition.warehouse_class.name.split('::').last
      "has_one :destination_record, **hud_assoc(:#{definition.hud_key}, '#{model_name}')"
    end

    private_class_method def self.generate_validations_code(definition)
      definition.columns.map do |column_config|
        column_name = column_config['name']
        validations = []

        validations << "validates :#{column_name}, presence: true" if column_config['required']
        validations << "validates :#{column_name}, length: { maximum: #{column_config['max_length']} }" if column_config['max_length']

        case column_config['type']
        when 'integer'
          validations << "validates :#{column_name}, numericality: { only_integer: true }, allow_blank: true"
        when 'boolean'
          validations << "validates :#{column_name}, inclusion: { in: [true, false, 0, 1, '0', '1', 'true', 'false'] }, allow_blank: true"
        end

        if column_config['validations']
          column_config['validations'].each do |validation|
            if validation.is_a?(String)
              # Handle string format validations
              if validation == 'NonBlank' && !column_config['required']
                validations << "validates :#{column_name}, presence: true"
              elsif validation.start_with?('inclusion:', 'length:', 'numericality:')
                # Handle inline validation strings like "inclusion: { in: %w[Client Enrollment] }"
                validations << "validates :#{column_name}, #{validation}"
              end
            elsif validation.is_a?(Hash)
              validation_class = validation['class']
              arguments = validation['arguments'] || {}
              validations << "validates :#{column_name}, #{validation_class.underscore}: { in: #{arguments['valid_options']} }" if validation_class == 'InclusionInSet'
            end
          end
        end

        validations
      end.flatten.uniq.join("\n    ")
    end

    # Generates a migration file for a specific custom file if tables don't exist
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [void]
    # @private
    private_class_method def self.generate_migration_for_file(definition)
      loader_table = "hmis_csv_2026_#{definition.class_name.underscore.pluralize}"
      importer_table = "hmis_2026_#{definition.class_name.underscore.pluralize}"

      # Check if tables exist
      loader_exists = GrdaWarehouseBase.connection.table_exists?(loader_table)
      importer_exists = GrdaWarehouseBase.connection.table_exists?(importer_table)

      return if loader_exists && importer_exists

      # Generate migration
      timestamp = Time.current.strftime('%Y%m%d%H%M%S')
      migration_name = "create_#{definition.class_name.underscore}_custom_tables"
      migration_file = "db/warehouse/migrate/#{timestamp}_#{migration_name}.rb"

      migration_content = generate_migration_content(
        definition: definition,
        loader_table: loader_table,
        importer_table: importer_table,
        loader_exists: loader_exists,
        importer_exists: importer_exists,
        migration_name: migration_name,
      )

      File.write(Rails.root.join(migration_file), migration_content)
      puts "Generated migration: #{migration_file}"
    end

    # Generates the content for a migration file
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param loader_table [String] Name of the loader table
    # @param importer_table [String] Name of the importer table
    # @param loader_exists [Boolean] Whether loader table exists
    # @param importer_exists [Boolean] Whether importer table exists
    # @param migration_name [String] Name of the migration class
    # @return [String] Migration file content
    # @private
    private_class_method def self.generate_migration_content(definition:, loader_table:, importer_table:, loader_exists:, importer_exists:, migration_name:)
      class_name = migration_name.camelize

      content = <<~MIGRATION
        # frozen_string_literal: true

        # THIS FILE IS AUTOGENERATED.
        class #{class_name} < ActiveRecord::Migration[7.1]
          def change
        #{generate_loader_table_migration(definition, loader_table) unless loader_exists}
        #{generate_importer_table_migration(definition, importer_table) unless importer_exists}
            # End generated migration content
          end
        end
      MIGRATION

      content
    end

    # Generates loader table creation code
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param table_name [String] Name of the loader table
    # @return [String] Migration code for loader table
    # @private
    private_class_method def self.generate_loader_table_migration(definition, table_name)
      columns = definition.real_columns.map do |col|
        "      t.string '#{col['name']}'"
      end.join("\n")

      # Use first real column for index (virtual columns shouldn't be used for indexing)
      first_column = definition.real_columns.first['name']

      <<~LOADER_TABLE
            # #{definition.class_name} loader table
            create_table :#{table_name} do |t|
        #{columns}

              # Standard loader columns
              t.references :data_source, null: false, index: true
              t.datetime :loaded_at, null: false
              t.references :loader, null: false, index: true
            end

            # Add indexes for loader table
            add_index :#{table_name}, [:#{first_column}, :data_source_id], name: 'idx_#{table_name.gsub('hmis_csv_2026_', '')}_id_ds'
      LOADER_TABLE
    end

    # Generates importer table creation code
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @param table_name [String] Name of the importer table
    # @return [String] Migration code for importer table
    # @private
    private_class_method def self.generate_importer_table_migration(definition, table_name)
      columns = definition.real_columns.map do |col|
        column_type = case col['type']
        when 'integer' then 'integer'
        when 'datetime', 'date' then 'datetime'
        when 'boolean' then 'boolean'
        else 'string'
        end
        "      t.#{column_type} '#{col['name']}'"
      end.join("\n")

      # Use first real column for index (virtual columns shouldn't be used for indexing)
      first_column = definition.real_columns.first['name']

      <<~IMPORTER_TABLE
            # #{definition.class_name} importer table
            create_table :#{table_name} do |t|
        #{columns}

              # Standard importer columns
              t.references :data_source, null: false, index: true
              t.references :importer_log, null: false, index: true
              t.datetime :pre_processed_at, null: false
              t.string :source_hash
              t.references :source, null: false, index: false
              t.string :source_type, null: false
              t.timestamp :dirty_at
              t.timestamp :clean_at
              t.boolean :should_import, default: true
            end

            # Add indexes for importer table
            add_index :#{table_name}, [:#{first_column}, :data_source_id], name: 'idx_#{table_name.gsub('hmis_2026_', '')}_imp_id_ds'
            add_index :#{table_name}, [:source_type, :source_id], name: 'idx_#{table_name.gsub('hmis_2026_', '')}_source'
      IMPORTER_TABLE
    end

    # Removes all custom model files generated by bootstrap_custom_models!
    #
    # This method removes:
    # - Loader model files from drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/
    # - Importer model files from drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/
    #
    # Note: This does NOT remove migration files or drop database tables.
    # You'll need to handle those separately if needed.  This is a convenience method for development.
    #
    # @return [void]
    def self.clean_custom_models!
      HmisCsvTwentyTwentySix.custom_files_config.definitions.each do |definition|
        remove_loader_model_file(definition)
        remove_importer_model_file(definition)
        remove_exporter_model_file(definition)
      end
    end

    private_class_method def self.remove_loader_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/loader/custom/#{definition.class_name.underscore}.rb")

      if File.exist?(file_path)
        File.delete(file_path)
        puts "Removed loader model: #{file_path}"
      else
        puts "Loader model not found: #{file_path}"
      end
    end

    private_class_method def self.remove_importer_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/importer/custom/#{definition.class_name.underscore}.rb")

      if File.exist?(file_path)
        File.delete(file_path)
        puts "Removed importer model: #{file_path}"
      else
        puts "Importer model not found: #{file_path}"
      end
    end

    private_class_method def self.remove_exporter_model_file(definition)
      file_path = Rails.root.join("drivers/hmis_csv_twenty_twenty_six/app/models/hmis_csv_twenty_twenty_six/exporter/custom/#{definition.class_name.underscore}.rb")

      if File.exist?(file_path)
        File.delete(file_path)
        puts "Removed exporter model: #{file_path}"
      else
        puts "Exporter model not found: #{file_path}"
      end
    end

    # Generates the export scope code based on the configuration
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [String] Ruby code for the export_scope method
    # @private
    private_class_method def self.generate_export_scope_code(definition)
      if definition.augments_export_class.present?
        export_class = definition.augments_export_class
        [
          "# Use the same export scope as the standard #{export_class.split('::').last} exporter",
          "#{export_class}.export_scope(**options)",
        ].join("\n      ")
      elsif definition.warehouse_class_name.present?
        # These files belong to existing warehouse data
        # If there's an export_limiting_column_value_mapping, we filter by owner relationships
        # If not, we export all records from the warehouse class for the relevant data sources
        available_owner_types = definition.export_limiting_column_value_mapping
        lines = ["warehouse_class = #{definition.warehouse_class_name}", '']

        # Check if we have export_limiting_column_value_mapping (owner-based filtering)
        # If not, we export all records from the warehouse class for the relevant data sources
        if available_owner_types.nil?
          lines += [
            '# No export limiting column - export all records for the relevant data sources',
            'data_source_ids = options[:project_scope].distinct.pluck(:data_source_id) if options[:project_scope]',
            'data_source_ids ||= [0] # if we can\'t determine any relevant data sources, include no data',
            'combined_scope = warehouse_class.where(data_source_id: data_source_ids)',
          ]
        else
          # Add the variables we'll need for owner-based filtering
          lines += [
            '# Create a union of scopes for each owner type, delegating to their export_scope',
            'scopes = []',
            '',
            '# Get the scope mapping from the custom base class',
            'scope_mapping = HmisCsvTwentyTwentySix::Exporter::Custom::Base.exporter_scope_mapping',
            '',
          ]
          # Generate the hash with each key-value pair on its own line for readability
          lines += [
            '{',
          ]
          available_owner_types.each do |(k, v)|
            lines << "  '#{k}' => '#{v}',"
          end
          lines += [
            '}.each do |granular_class_name, owner_type|',
            '  export_class = "HmisCsvTwentyTwentySix::Exporter::#{granular_class_name}".constantize',
            '  next unless export_class.respond_to?(:export_scope)',
            '',
            '  # Get the IDs of records being exported for this owner type',
            '  # Each exporter requires different scope parameters, so we provide only what it needs',
            '  required_scope_param = scope_mapping[granular_class_name]',
            '  if required_scope_param && options.key?(required_scope_param)',
            '    # Build the arguments hash with only the required scope parameter and export',
            '    scope_args = { required_scope_param => options[required_scope_param], export: options[:export] }',
            '    owner_ids_scope = export_class.export_scope(**scope_args).select(:id)',
            '  else',
            '    # Fallback: skip this exporter if we don\'t have the required scope',
            '    Rails.logger.warn "Skipping #{granular_class_name} exporter - missing required scope #{required_scope_param}"',
            '    next',
            '  end',
            '',
            '  # Find records that reference these exported records',
            '  scope = warehouse_class.where(',
            '    owner_type: owner_type,',
            '    owner_id: owner_ids_scope,',
            '  )',
            '',
            '  scopes << scope',
            'end',
            '',
            '# Union all the scopes together',
            'return warehouse_class.none if scopes.empty?',
            '',
            'combined_scope = scopes.shift',
            'scopes.each do |scope|',
            '  combined_scope = combined_scope.or(scope)',
            'end',
          ]
        end

        lines += [
          '',
          'combined_scope',
        ]

        content = ''
        lines.each_with_index do |line, index|
          content += '      ' if line.present? && index.positive?
          content += line
          content += "\n" if index != lines.length - 1
        end
        content
      else
        return "# No export class specified\n      []"
      end
    end

    # Generates the adjust_keys method code based on the configuration
    #
    # @param definition [CustomFileDefinition] Definition object for the custom file
    # @return [String] Ruby code for the adjust_keys method
    # @private
    private_class_method def self.generate_adjust_keys_code(definition)
      export_class = definition.augments_export_class
      if export_class.present?

        # rubocop:disable Layout/HeredocIndentation
        <<~RUBY.strip
    def self.adjust_keys(row, export)
          # Delegate to the standard exporter's adjust_keys method
          #{export_class}.adjust_keys(row, export)
        end
        RUBY
        # rubocop:enable Layout/HeredocIndentation
      else
        # rubocop:disable Layout/HeredocIndentation
        <<~RUBY.strip
    def self.adjust_keys(row, _export)
          row.UserID = row.user_id || 'op-system'
          row[:#{definition.hud_key}] = row.id

          row
        end
        RUBY
        # rubocop:enable Layout/HeredocIndentation
      end
    end

    # Generates the hmis_configuration method code based on the YAML columns
    private_class_method def self.generate_hmis_configuration_code(definition)
      column_configs = definition.columns.map do |col|
        type = col['type'].in?(['integer', 'datetime', 'date', 'boolean']) ? ":#{col['type']}" : ':string'
        options = []
        options << "limit: #{col['max_length']}" if col['max_length']
        options << 'null: false' if col['required']
        options_str = options.any? ? ", #{options.join(', ')}" : ''

        "        #{col['name']}: { type: #{type}#{options_str} },"
      end.join("\n")

      # rubocop:disable Layout/HeredocIndentation
      <<~RUBY.strip
    def self.hmis_configuration(version: '2026') # rubocop:disable Lint/UnusedMethodArgument
      {
#{column_configs}
      }
    end
      RUBY
      # rubocop:enable Layout/HeredocIndentation
    end
  end
end
