# frozen_string_literal: true

FactoryBot.define do
  factory :hmis_ce_opportunity, class: 'Hmis::Ce::Opportunity' do
    # Rules for using this factory in order to ensure consistency:
    # - If you don't provide anything, the factory will create an internally consistent opportunity. Meaning,
    #   - the project on the opportunity == the project on the unit
    #   - the project's data source == the unit's workflow template's data source
    # - If you do provide any of these attributes, you have to also provide the data source,
    #   otherwise there will be internal inconsistency and the record generated by the factory might not be valid.

    transient do
      data_source { build :hmis_data_source }
      workflow_template { association :hmis_workflow_definition_template, data_source: data_source }
    end

    sequence(:name) { |n| "Opportunity #{n}" }
    status { 'open' }
    project { association :hmis_hud_project, data_source: data_source }

    unit do
      unit_group = association :hmis_unit_group, project: project, workflow_template_identifier: workflow_template.identifier
      association :hmis_unit, project: project, unit_group: unit_group
    end
  end
end
