# frozen_string_literal: true

FactoryBot.define do
  factory :hmis_ce_opportunity, class: 'Hmis::Ce::Opportunity' do
    # Rules for using this factory in order to ensure consistency:
    # - If you don't provide anything, the factory will create an internally consistent opportunity:
    #   - the project on the opportunity == the project on the unit
    #   - the project/unit's data source == the workflow template's data source
    # - If you do provide any of these attributes, you have to also provide the others,
    #   otherwise there will be internal inconsistency and the record generated by the factory might not be valid.

    transient do
      data_source { build :hmis_data_source }
      workflow_template { association :hmis_workflow_definition_template, data_source: data_source }
    end

    sequence(:name) { |n| "Opportunity #{n}" }
    status { 'open' }
    project { association :hmis_hud_project, data_source: data_source }

    # Hooks to make the Opportunity factory return a valid opportunity *both* when creating (saving) a record *and* when just building it:

    # In an after(:build) hook, create the associated unit and unit group. (All opportunities should have units and all units are now in groups)
    after(:build) do |opportunity, evaluator|
      next if opportunity.unit.present?

      ug = build(:hmis_unit_group, project: opportunity.project, workflow_template: evaluator.workflow_template)
      opportunity.unit = build(:hmis_unit, project: opportunity.project, unit_group: ug)
    end

    # In a before(:save) hook, save the unit, so the opportunity validations pass
    before(:create) do |opportunity|
      opportunity.project.save! unless opportunity.project.persisted?
      opportunity.unit.unit_group.save! unless opportunity.unit.unit_group.nil? || opportunity.unit.unit_group.persisted?
      opportunity.unit.save! unless opportunity.unit.persisted?
    end
  end
end
