# frozen_string_literal: true

FactoryBot.define do
  factory :hmis_ce_opportunity, class: 'Hmis::Ce::Opportunity' do
    # Rules for using this factory in order to ensure consistency:
    # - If you don't provide anything, the factory will create an internally consistent opportunity.
    #   - The project's data source == the template's data source
    # - If you do provide any of these attributes, you have to also provide the data source,
    #   otherwise there will be internal inconsistency and the record generated by the factory might not be valid.

    transient do
      data_source { build :hmis_data_source }
    end

    sequence(:name) { |n| "Opportunity #{n}" }
    project { association :hmis_hud_project, data_source: data_source }
    workflow_template { association :hmis_workflow_definition_template, data_source: data_source }
    unit { association :hmis_unit, project: project }
  end
end
