# frozen_string_literal: true

FactoryBot.define do
  factory :hmis_ce_referral, class: 'Hmis::Ce::Referral' do
    # Rules for using this factory in order to ensure consistency:
    # - If you don't specify anything, the factory will create an internally consistent referral.
    #   - The target project's data source == the template's data source
    #   - The instance's template is the same as the opportunity's template
    #   - The client is also in the correct data source
    # - If you do provide any of these attributes, you have to also provide the data source,
    #   otherwise there will be internal inconsistency and the record generated by the factory might not be valid.

    transient do
      data_source { build :hmis_data_source }
      project { build :hmis_hud_project, data_source: data_source }
      workflow_template { build :hmis_workflow_definition_template, data_source: data_source }
    end

    opportunity { association :hmis_ce_opportunity, project: project, workflow_template: workflow_template }
    workflow_instance { association :hmis_workflow_execution_instance, template: workflow_template }
    client { association :hmis_hud_client, data_source: data_source }
    referred_by { association :hmis_user, data_source: data_source }
  end
end
