<% require File.expand_path('../lib/util/rails_db_uri_extractor', __FILE__) %>
databases:
  warehouse:
    url: <%= RailsDbUriExtractor.extract_uri(env: Rails.env, name: 'warehouse') %>

# Minimum time for long running queries
long_running_query_sec: 30

# Minimum average time for slow queries
slow_query_ms: 1000

# Minimum calls for slow queries
slow_query_calls: 100

# Minimum connections for high connections warning
# total_connections_threshold: 500

# Explain functionality
# explain: true / false / analyze

# Statement timeout for explain
explain_timeout_sec: 10

# Visualize URL for explain
# visualize_url: https://...

# Time zone (defaults to app time zone)
# time_zone: "Pacific Time (US & Canada)"

# Basic authentication
# username: admin
# password: <%= ENV["PGHERO_PASSWORD"] %>

# Stats database URL (defaults to app database)
stats_database_url: <%= RailsDbUriExtractor.extract_uri(env: Rails.env, name: 'primary') %>

# AWS configuration (defaults to app AWS config)
# aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
# aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
# aws_region: us-east-1

# Filter data from queries (experimental)
# filter_data: true
