# frozen_string_literal: true

require 'rails_helper'
require_relative '../../../../hud_spm_report/spec/models/fy2024/shared_context'

RSpec.describe 'Performance Measurement and SPM Alignment', type: :model do
  include_context 'SPM test setup'

  # Shared context for running both reports with the same data
  shared_context 'report generation' do
    before do
      # Generate the service history records for enrollments
      GrdaWarehouse::Tasks::ServiceHistory::Enrollment.find_each(&:rebuild_service_history!)

      # Create the report filter
      spm_report_filter = default_filter.dup
      spm_report_filter.update(project_ids: project_ids)

      # Step 1: Run the Performance Measurement report
      @pm_report = PerformanceMeasurement::Report.new(
        user_id: user.id,
      )
      @pm_report.filter = spm_report_filter
      @pm_report.update_goal_configuration!
      @pm_report.save!
      @pm_report.run_and_save!
      @pm_report.reload

      # Step 2: Get the SPM report that was generated by the PM report
      @spm_report = HudReports::ReportInstance.find(@pm_report.reporting_spm_id)
    end
  end

  describe 'measure 1 values alignment' do
    let(:spm_question) { 'Measure 1' }
    let(:measure_class) { HudSpmReport::Generators::Fy2024::MeasureOne }
    let(:project_ids) { [@es_project.id, @th_project.id] }

    before do
      PerformanceMeasurement::Goal.ensure_default
      # Create ES and TH projects
      @es_project = create_project(project_type: 0) # ES-EE
      @th_project = create_project(project_type: 2) # TH

      # Create clients with different homeless patterns
      @client1 = create_client_with_warehouse_link
      @client2 = create_client_with_warehouse_link
      @client3 = create_client_with_warehouse_link

      # Client 1: Simple ES stay (75 days)
      create_enrollment(
        client: @client1,
        project: @es_project,
        entry_date: '2022-11-01'.to_date,
        exit_date: '2023-01-15'.to_date,
      )

      # Client 2: ES stay followed by TH stay with gap
      create_enrollment(
        client: @client2,
        project: @es_project,
        entry_date: '2022-10-15'.to_date,
        exit_date: '2022-12-15'.to_date,
      )

      create_enrollment(
        client: @client2,
        project: @th_project,
        entry_date: '2022-12-20'.to_date,
        exit_date: '2023-01-20'.to_date,
      )

      # Client 3: Overlapping ES stays
      create_enrollment(
        client: @client3,
        project: @es_project,
        entry_date: '2022-10-01'.to_date,
        exit_date: '2022-12-01'.to_date,
      )
      create_enrollment(
        client: @client3,
        project: @es_project,
        entry_date: '2022-11-15'.to_date,
        exit_date: '2023-01-15'.to_date,
      )
    end

    include_context 'report generation'

    it 'has the same client count in both reports' do
      # SPM report universe count
      spm_client_count = @spm_report.answer(question: '1a', cell: 'B2').summary

      # PM report client count
      pm_client_count = @pm_report.result_for(:count_of_homeless_clients_in_range).primary_value

      # Both should have 3 clients
      expect(spm_client_count).to eq(3)
      expect(pm_client_count).to eq(3)
    end

    it 'has aligned average days homeless value for ES, SH and TH' do
      # SPM report average days
      spm_average = @spm_report.answer(question: '1a', cell: 'D2').summary.to_f

      # PM report average days
      pm_result = @pm_report.result_for(:length_of_homeless_time_homeless_average)
      pm_average = pm_result.primary_value.to_f

      # They should match
      expect(pm_average).to be_within(0.1).of(spm_average)
    end

    it 'has aligned median days homeless value for ES, SH and TH' do
      # SPM report median days
      spm_median = @spm_report.answer(question: '1a', cell: 'G2').summary.to_f

      # PM report median days
      pm_result = @pm_report.result_for(:length_of_homeless_time_homeless_median)
      pm_median = pm_result.primary_value.to_f

      expect(pm_median).to be_within(0.1).of(spm_median)
    end
  end

  describe 'measure 7 values alignment' do
    let(:spm_question) { 'Measure 7' }
    let(:measure_class) { HudSpmReport::Generators::Fy2024::MeasureSeven }
    let(:project_ids) { [@es_project.id, @th_project.id, @ph_project.id] }

    before do
      PerformanceMeasurement::Goal.ensure_default
      # Create projects of different types
      @es_project = create_project(project_type: 0) # ES-EE
      @th_project = create_project(project_type: 2) # TH
      @ph_project = create_project(project_type: 3) # PH

      # Create clients with different exit scenarios
      @client1 = create_client_with_warehouse_link
      @client2 = create_client_with_warehouse_link
      @client3 = create_client_with_warehouse_link

      # Client 1: Exit from ES to permanent housing
      create_enrollment(
        client: @client1,
        project: @es_project,
        entry_date: '2022-11-01'.to_date,
        exit_date: '2023-01-15'.to_date,
        destination: 410, # Rental by client, no subsidy (permanent)
      )

      # Client 2: Exit from TH to temporary destination
      create_enrollment(
        client: @client2,
        project: @th_project,
        entry_date: '2022-10-15'.to_date,
        exit_date: '2022-12-15'.to_date,
        destination: 118, # Safe Haven (non-permanent)
      )

      # Client 3: PH stayer with move-in date
      create_enrollment(
        client: @client3,
        project: @ph_project,
        entry_date: '2022-10-01'.to_date,
        exit_date: nil,
        move_in_date: '2022-11-01'.to_date,
      )
    end

    include_context 'report generation'

    it 'has the same permanent housing exit rate in both reports' do
      # SPM report successful placement percentage for ES/TH/SH/RRH exits
      spm_percentage = @spm_report.answer(question: '7b.1', cell: 'C4').summary.to_f

      # PM report success rate
      pm_result = @pm_report.result_for(:es_sh_th_rrh_positive_destinations)
      pm_percentage = pm_result.primary_value.to_f

      # They should match
      expect(pm_percentage).to be_within(0.1).of(spm_percentage)
    end

    it 'has the same PH retention or exit rate in both reports' do
      # SPM report retention percentage for PH projects
      spm_percentage = @spm_report.answer(question: '7b.2', cell: 'C4').summary.to_f

      # PM report retention rate
      pm_result = @pm_report.result_for(:moved_in_positive_destinations)
      pm_percentage = pm_result.primary_value.to_f

      # They should match
      expect(pm_percentage).to be_within(0.1).of(spm_percentage)
    end
  end

  describe 'measure 2 values alignment' do
    let(:spm_question) { 'Measure 2' }
    let(:measure_class) { HudSpmReport::Generators::Fy2024::MeasureTwo }
    let(:project_ids) { [@es_project.id, @ph_project.id] }

    before do
      PerformanceMeasurement::Goal.ensure_default
      # Create ES and PH projects
      @es_project = create_project(project_type: 0) # ES-EE
      @ph_project = create_project(project_type: 3) # PH

      # Create clients with different return patterns
      @client1 = create_client_with_warehouse_link
      @client2 = create_client_with_warehouse_link
      @client3 = create_client_with_warehouse_link

      # For SPM Measure 2, we need to create exits from two years ago
      # and then returns within the reporting period

      # Client 1: Exit to PH then returns to ES within 6 months
      create_enrollment(
        client: @client1,
        project: @ph_project,
        entry_date: '2021-03-01'.to_date,
        exit_date: '2021-06-15'.to_date,
        destination: 410, # Rental by client, no subsidy (permanent)
      )

      create_enrollment(
        client: @client1,
        project: @es_project,
        entry_date: '2021-08-01'.to_date, # About 1.5 months after exit
        exit_date: '2021-09-15'.to_date,
      )

      # Client 2: Exit to PH then returns to ES within 12 months
      create_enrollment(
        client: @client2,
        project: @ph_project,
        entry_date: '2021-02-01'.to_date,
        exit_date: '2021-04-15'.to_date,
        destination: 410, # Rental by client, no subsidy (permanent)
      )

      create_enrollment(
        client: @client2,
        project: @es_project,
        entry_date: '2022-01-01'.to_date, # About 8.5 months after exit
        exit_date: '2022-02-15'.to_date,
      )

      # Client 3: Exit to PH and doesn't return
      create_enrollment(
        client: @client3,
        project: @ph_project,
        entry_date: '2021-03-01'.to_date,
        exit_date: '2021-05-15'.to_date,
        destination: 410, # Rental by client, no subsidy (permanent)
      )
    end

    include_context 'report generation'

    it 'has the same 6-month return rate in both reports' do
      # SPM report 6-month return percentage
      spm_percentage = @spm_report.answer(question: '2a and 2b', cell: 'D7').summary.to_f

      # PM report 6-month return rate
      pm_result = @pm_report.result_for(:returned_in_six_months)
      pm_percentage = pm_result.primary_value.to_f

      # They should match
      expect(pm_percentage.round).to eq(spm_percentage.round)
    end

    it 'has the same 12-month return rate in both reports' do
      # SPM report 12-month return percentage (includes 0-6 months and 6-12 months)
      spm_percentage = @spm_report.answer(question: '2a and 2b', cell: 'F7').summary.to_f

      # PM report 12-month return rate
      pm_result = @pm_report.result_for(:returned_in_one_year)
      pm_percentage = pm_result.primary_value.to_f

      # They should match
      expect(pm_percentage).to be_within(0.1).of(spm_percentage)
    end

    it 'has the same 24-month return rate in both reports' do
      # SPM report 24-month return percentage
      spm_percentage = @spm_report.answer(question: '2a and 2b', cell: 'J7').summary.to_f

      # PM report 24-month return rate
      pm_result = @pm_report.result_for(:returned_in_two_years)
      pm_percentage = pm_result.primary_value.to_f

      # They should match
      expect(pm_percentage.round).to eq(spm_percentage.round)
    end

    it 'has the same count of total exits to permanent housing' do
      # SPM report total exits to permanent housing
      spm_count = @spm_report.answer(question: '2a and 2b', cell: 'B7').summary

      # PM report denominator for returns calculation
      pm_result = @pm_report.result_for(:returned_in_six_months)
      pm_count = pm_result.reporting_denominator

      # They should match
      expect(pm_count).to eq(spm_count)
    end
  end
end
