services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.5.1
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080"
    volumes:
      # let traefik know where to look for the certs.
      - ./tools/certs:/tools/certs
      - ./tools/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  default:
    external: true
    name: development
