###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::CustomFileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Loader::Custom
  class CustomGender < HmisCsvTwentyTwentySix::Loader::Custom::Base
    self.table_name = 'hmis_csv_2026_custom_genders'
    self.hud_key = :PersonalID
    @custom_file_config = HmisCsvTwentyTwentySix.custom_files_config.for('CustomGender.csv')
  end
end
