###
# Copyright 2016 - 2025 Green River Data Analysis, LLC
#
# License detail: https://github.com/greenriver/hmis-warehouse/blob/production/LICENSE.md
###

# frozen_string_literal: true

# THIS FILE IS AUTOGENERATED. DO NOT EDIT.
# Re-run HmisCsvTwentyTwentySix::Custom::FileManager.bootstrap_custom_models! to regenerate.

module HmisCsvTwentyTwentySix::Loader::Custom
  class CustomEnrollmentFy26Deprecation < HmisCsvTwentyTwentySix::Loader::Custom::Base
    self.table_name = 'hmis_csv_2026_custom_enrollment_fy26_deprecations'
    self.hud_key = :EnrollmentID
    @custom_file_definition = HmisCsvTwentyTwentySix.custom_files_config.find_definition('CustomEnrollmentFY26Deprecations.csv')
  end
end
