FROM quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e

LABEL org.opencontainers.image.source="https://github.com/greenriver/hmis-warehouse"

CMD ["server", "/data"]
