# config/hmis_csv_twenty_twenty_six_custom_files.yml
custom_files:
  - filename: "CustomDataElement.csv"
    class_name: "CustomDataElement"
    required: false
    description: "Custom data element values"
    augments_warehouse_table: "Hmis::Hud::CustomDataElement"
    definition_class: "CustomDataElementDefinition"
    definition_key: "CustomDataElementDefinitionID"
    columns:
      - name: "CustomDataElementID"
        type: "string"
        required: true
        validations: ["NonBlank"]
      - name: "CustomDataElementDefinitionID"
        type: "string"
        required: true
        validations: ["NonBlank"]
      - name: "RecordType"
        type: "string"
        required: true
        validations:
          - class: "InclusionInSet"
            arguments:
              valid_options:
                ["Client", "Enrollment", "Exit", "Project", "Organization"]
      - name: "RecordID"
        type: "string"
        required: true
        validations: ["NonBlank"]
      - name: "Value"
        type: "string"
        required: false
      - name: "DataCollectionStage"
        type: "integer"
        required: false
      - name: "InformationDate"
        type: "date"
        required: false
      - name: "UserID"
        type: "string"
      - name: "DateCreated"
        type: "datetime"
      - name: "DateUpdated"
        type: "datetime"
      - name: "DateDeleted"
        type: "datetime"
      - name: "ExportID"
        type: "string"
