injectRequestHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
  - name: X-Forwarded-Access-Token
    values:
      - claim: access_token
  - name: Authorization
    values:
      - claim: id_token
        prefix: "Bearer "
injectResponseHeaders:
  - name: X-Auth-Request-User
    values:
      - claim: user
  - name: X-Auth-Request-Email
    values:
      - claim: email
  - name: X-Auth-Request-Preferred-Username
    values:
      - claim: preferred_username
  - name: X-Auth-Request-Groups
    values:
      - claim: groups
  - name: X-Auth-Request-Access-Token
    values:
      - claim: access_token
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
providers:
  - ADFSConfig: {}
    azureConfig:
      tenant: common
    backendLogoutURL: "https://dex.dev.test/dex/auth/logout"
    bitbucketConfig: {}
    clientID: hmis-warehouse
    clientSecret: "dtm0zv-OaNMLiq2V00I1IpIFv_ZCsP_m-V0FYubBpLg="
    githubConfig: {}
    gitlabConfig: {}
    googleConfig: {}
    id: Dex
    keycloakConfig: {}
    loginGovConfig: {}
    loginURLParameters:
      - name: connector_id
        allow:
          - value: local
          - value: github_idp
          - value: zitadel

    microsoftEntraIDConfig: {}
    name: Dex
    oidcConfig:
      audienceClaims:
        - aud
      emailClaim: email
      groupsClaim: groups
      insecureSkipNonce: true
      issuerURL: https://dex.dev.test/dex
      userIDClaim: email
    provider: oidc
    scope: openid email profile federated:id
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null
upstreamConfig:
  upstreams:
    - flushInterval: 1s
      id: warehouse
      passHostHeader: true
      path: /
      proxyWebSockets: true
      timeout: 30s
      uri: http://web:3000
