#!/usr/bin/env bash
# Generates oauth2-proxy alpha-config files from templates in docker/auth/.
# Output goes to dev/auth/ which is gitignored.
#
# The active templates contain no ${...} placeholders — their OIDC clientSecrets are
# hardcoded to match Dex's staticClients — so this script does no substitution. It copies
# each template into dev/auth/ and prepends a provenance/SHA header. The only load-bearing
# dev secret in this stack is OAUTH2_PROXY_COOKIE_SECRET (oauth2-proxy's cookie-encryption
# key), which the .cfg files do not set, so it falls back to this env var at runtime.
# This script validates that it is present in .env.development.local.
#
# Run once after initial setup and again if a template file changes.
# The script is idempotent — it skips files whose template has not changed
# since the last generation (tracked via SHA256 comment in the output file).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/docker/auth/templates"
OUTPUT_DIR="$REPO_ROOT/dev/auth"
ENV_FILE="$REPO_ROOT/.env.development.local"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found. Copy sample.env and set required values." >&2
  exit 1
fi

# Echoes trimmed value on stdout with status 0; status 1 and no output when missing or empty.
read_env_line() {
  local key="$1" val
  val="$(grep "^${key}=" "$ENV_FILE" | sed "s/^${key}=//;s/^\"//;s/\"$//" || true)"
  if [[ -z "$val" ]]; then
    return 1
  fi
  printf '%s' "$val"
  return 0
}

# OAUTH2_PROXY_COOKIE_SECRET is the only load-bearing dev secret in this stack.
OAUTH2_COOKIE_SECRET="$(read_env_line OAUTH2_PROXY_COOKIE_SECRET || true)"

if [[ -z "$OAUTH2_COOKIE_SECRET" ]]; then
  echo "Error: OAUTH2_PROXY_COOKIE_SECRET is missing, set a OAUTH2_PROXY_COOKIE_SECRET in: $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

TEMPLATES=(
  dev.oauth2-proxy-warehouse.yaml
  dev.oauth2-proxy-hmis.yaml
  dev.oauth2-proxy-hmis-backend.yaml
)

for NAME in "${TEMPLATES[@]}"; do
  TEMPLATE="$TEMPLATE_DIR/$NAME"
  OUTPUT="$OUTPUT_DIR/$NAME"

  TEMPLATE_SHA=$(openssl dgst -sha256 "$TEMPLATE" | awk '{print $2}')

  if [[ -f "$OUTPUT" ]]; then
    STORED_SHA=$(grep '^# template-sha:' "$OUTPUT" | awk '{print $3}')
    if [[ "$TEMPLATE_SHA" == "$STORED_SHA" ]]; then
      echo "$NAME: up to date"
      continue
    fi
  fi

  {
    echo "# Generated by docker/auth/generate-dev-auth.sh — do not edit directly."
    echo "# Re-run the script if the template in docker/auth/ changes."
    echo "# template-sha: $TEMPLATE_SHA"
    cat "$TEMPLATE"
  } > "$OUTPUT"

  echo "$NAME: generated"
done
