#!/usr/bin/env bash
# Generates oauth2-proxy alpha-config files from templates in docker/auth/.
# Substitutes ${JWT_SECRET} from .env.development.local into templates and requires
# OAUTH2_PROXY_COOKIE_SECRET / OAUTH2_PROXY_CLIENT_SECRET to be set there too (compose uses them).
# Output goes to dev/auth/ which is gitignored.
#
# Run once after initial setup and again if a template file changes.
# The script is idempotent — it skips files whose template has not changed
# since the last generation (tracked via SHA256 comment in the output file).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/docker/auth/templates"
OUTPUT_DIR="$REPO_ROOT/dev/auth"
ENV_FILE="$REPO_ROOT/.env.development.local"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found. Copy sample.env and set required values." >&2
  exit 1
fi

# Echoes trimmed value on stdout with status 0; status 1 and no output when missing or empty.
read_env_line() {
  local key="$1" val
  val="$(grep "^${key}=" "$ENV_FILE" | sed "s/^${key}=//;s/^\"//;s/\"$//" || true)"
  if [[ -z "$val" ]]; then
    return 1
  fi
  printf '%s' "$val"
  return 0
}

# Read and validate JWT_SECRET, OAUTH2_COOKIE_SECRET, OAUTH2_CLIENT_SECRET
# Note: only JWT_SECRET is required for this script, but we validate all three for completeness.
JWT_SECRET="$(read_env_line JWT_SECRET || true)"
OAUTH2_COOKIE_SECRET="$(read_env_line OAUTH2_PROXY_COOKIE_SECRET || true)"
OAUTH2_CLIENT_SECRET="$(read_env_line OAUTH2_PROXY_CLIENT_SECRET || true)"

if [[ -z "$JWT_SECRET" ]]; then
  echo "Error: JWT_SECRET is missing, set a JWT_SECRET in: $ENV_FILE" >&2
  exit 1
fi

if [[ -z "$OAUTH2_COOKIE_SECRET" ]]; then
  echo "Error: OAUTH2_PROXY_COOKIE_SECRET is missing, set a OAUTH2_PROXY_COOKIE_SECRET in: $ENV_FILE" >&2
  exit 1
fi

if [[ -z "$OAUTH2_CLIENT_SECRET" ]]; then
  echo "Error: OAUTH2_PROXY_CLIENT_SECRET is missing, set a OAUTH2_PROXY_CLIENT_SECRET in: $ENV_FILE" >&2
  exit 1
fi

# ensure JWT_SECRET, OAUTH2_COOKIE_SECRET, OAUTH2_CLIENT_SECRET are set to the same value
if [[ "$JWT_SECRET" != "$OAUTH2_COOKIE_SECRET" || "$JWT_SECRET" != "$OAUTH2_CLIENT_SECRET" ]]; then
  echo "Error: JWT_SECRET, OAUTH2_COOKIE_SECRET, OAUTH2_CLIENT_SECRET are not set to the same value in: $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

TEMPLATES=(
  dev.oauth2-proxy-warehouse.yaml
  dev.oauth2-proxy-hmis.yaml
  dev.oauth2-proxy-hmis-backend.yaml
  dev.oauth2-proxy.yaml
)

for NAME in "${TEMPLATES[@]}"; do
  TEMPLATE="$TEMPLATE_DIR/$NAME"
  OUTPUT="$OUTPUT_DIR/$NAME"

  TEMPLATE_SHA=$(openssl dgst -sha256 "$TEMPLATE" | awk '{print $2}')

  if [[ -f "$OUTPUT" ]]; then
    STORED_SHA=$(grep '^# template-sha:' "$OUTPUT" | awk '{print $3}')
    if [[ "$TEMPLATE_SHA" == "$STORED_SHA" ]]; then
      echo "$NAME: up to date"
      continue
    fi
  fi

  {
    echo "# Generated by docker/auth/generate-dev-auth.sh — do not edit directly."
    echo "# Re-run the script if the template in docker/auth/ changes."
    echo "# template-sha: $TEMPLATE_SHA"
    sed "s|\${JWT_SECRET}|$JWT_SECRET|g" "$TEMPLATE"
  } > "$OUTPUT"

  echo "$NAME: generated"
done
