#!/usr/bin/env bash
# Generates oauth2-proxy alpha-config files from templates in docker/auth/.
# Substitutes ${JWT_SECRET} with the value from .env.development.local.
# Output goes to dev/auth/ which is gitignored.
#
# Run once after initial setup and again if a template file changes.
# The script is idempotent — it skips files whose template has not changed
# since the last generation (tracked via SHA256 comment in the output file).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/docker/auth"
OUTPUT_DIR="$REPO_ROOT/dev/auth"
ENV_FILE="$REPO_ROOT/.env.development.local"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found. Copy sample.env and set required values." >&2
  exit 1
fi

JWT_SECRET=$(grep '^JWT_SECRET=' "$ENV_FILE" | sed 's/^JWT_SECRET=//;s/^"//;s/"$//')
if [[ -z "$JWT_SECRET" ]]; then
  echo "Error: JWT_SECRET is not set in $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

TEMPLATES=(
  dev.oauth2-proxy-warehouse.yaml
  dev.oauth2-proxy-hmis.yaml
  dev.oauth2-proxy-hmis-backend.yaml
  dev.oauth2-proxy.yaml
)

for NAME in "${TEMPLATES[@]}"; do
  TEMPLATE="$TEMPLATE_DIR/$NAME"
  OUTPUT="$OUTPUT_DIR/$NAME"

  TEMPLATE_SHA=$(openssl dgst -sha256 "$TEMPLATE" | awk '{print $2}')

  if [[ -f "$OUTPUT" ]]; then
    STORED_SHA=$(grep '^# template-sha:' "$OUTPUT" | awk '{print $3}')
    if [[ "$TEMPLATE_SHA" == "$STORED_SHA" ]]; then
      echo "$NAME: up to date"
      continue
    fi
  fi

  {
    echo "# Generated by docker/auth/generate-dev-auth.sh — do not edit directly."
    echo "# Re-run the script if the template in docker/auth/ changes."
    echo "# template-sha: $TEMPLATE_SHA"
    sed "s|\${JWT_SECRET}|$JWT_SECRET|g" "$TEMPLATE"
  } > "$OUTPUT"

  echo "$NAME: generated"
done
