#!/usr/bin/env ruby

require_relative 'lib/ecs_tools'
require_relative 'lib/command_args'

puts "Clearing local and remote pre-cache image..."

args = CommandArgs.new
deployment = args.deployments.first
deployer = Deployer.new(**deployment)

EcsTools.new.clear_cache!(deployer.repo_name)
