#!/usr/bin/env ruby

require_relative 'lib/command_args'
require_relative 'lib/deployer'

args = CommandArgs.new

args.deployments.each do |deployment|
  puts "Deploying #{deployment[:target_group_name]}..."
  Deployer.new(**deployment).run!
end

EcsTools.new.poll_state_until_stable!(CommandArgs.cluster)

puts "Updating one ECS instance agent if needed."
EcsTools.new.update_ecs_agents!(CommandArgs.cluster)
