#!/usr/bin/env ruby

require_relative 'lib/command_args'
require_relative 'lib/deployer'

args = CommandArgs.new

args.deployments.each_with_index do |deployment, idx|
  puts "Deploying #{deployment[:target_group_name]} #{idx}..."

  # If this is not the first deployment in a group, skip the git check, so that it doesn't fail
  # mid-group if a new commit is pushed.
  deployment[:skip_remote_git_check] = true unless idx.zero?

  Deployer.new(**deployment).run!

  # poll between deployments to prevent scaling out too much while we have
  # double the web containers.
  # i.e. don't proceed until it has stabilized
  EcsTools.new.poll_state_until_stable!(CommandArgs.cluster, max_unfinished: 4)
end
EcsTools.new.poll_state_until_stable!(CommandArgs.cluster)

puts 'Updating one ECS instance agent if needed.'
EcsTools.new.update_ecs_agents!(CommandArgs.cluster)
