#!/usr/bin/env ruby

require_relative 'lib/command_args'
require_relative 'lib/deployer'

args = CommandArgs.new

args.deployments.each do |deployment|
  puts "Deploying #{deployment[:target_group_name]}..."
  Deployer.new(**deployment).run_migrations!
end
