#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'lib/ecs_tools'
require_relative 'lib/command_args'

EcsTools.new.poll_state_until_stable!(CommandArgs.cluster, failures: ARGV[0] == '--failures')
