#!/usr/bin/env ruby

# This creates the RDS instance for an installation.
# It does not set up databases or database users.
# databases/users are done in ansible
# bootstrapping each database is via the boostrap_databases script
# in this directory.

require_relative 'lib/make_rds'

if ENV['AWS_PROFILE'].nil?
  puts "Set your AWS_PROFILE variable first"
  exit
end

raise "Set database instance name as first arg" if ARGV[0].nil?

MakeRDS.new(name: ARGV[0]).run!
