#!/usr/bin/env ruby

require_relative 'lib/ecs_tools'
require_relative 'lib/command_args'

if ENV['AWS_PROFILE'].nil?
  puts "Set your AWS_PROFILE variable first"
  exit
end

EcsTools.new.update_ecs_agents!(CommandArgs.cluster)
