name: Rubocop
on:
  pull_request:
    branches:
      - '*'
      - '**/*'
concurrency:
  group: ${{ github.ref }}-rubocop
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-22.04

    # Docker Hub image that the job executes in
    container: ruby:3.3.7-alpine3.20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 'Container Setup'
        id: container-setup
        uses: ./.github/workflows/container_setup

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          echo "{ruby}={$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .rb$ | xargs)}"

      - id: rubocop
        name: Run Rubocop
        # only run there are changed files
        # if: ${{steps.changed-files.outputs.ruby}}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.ruby }}
        run: |
          echo ${{steps.changed-files.outputs.ruby}}
          echo $ALL_CHANGED_FILES
          ignore_patterns="db/schema.rb\|bin/rails\|bin/rake\|bin/bundle"
          files=`echo "${ALL_CHANGED_FILES}" | tr " " "\n" | grep -v $ignore_patterns | grep "**/*.rb" | tr "\n" " ./"`
          num=`echo $files | wc -w`
          echo $files
          if [ $num -gt 0 ]; then bundle exec rubocop --config ./.rubocop.yml $files; else echo "No changed ruby files"; fi
      - id: eslint
        name: Run ESLint
        run: |
          yarn install --frozen-lockfile
          yarn lint --quiet
