name: Todo or Die

on:
  # NOTE: runs on both PRs and pulls. This would normally cause redundant jobs to run but there are conditions on github.event_name in the matrix to avoid this. In particular, we want the system tests to run only on PR so we can use the base_ref to infer the appropriate release branch name in the hmis FE repo (see issue #6566)
  push:
    branches:
      - '*'
      - '**/*'
  pull_request:
    branches:
      - '*'
      - '**/*'
concurrency:
  group: ${{ github.ref }}-todo-or-die
  cancel-in-progress: true

jobs:
  todo_or_die_check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: ['3.3.7']
      fail-fast: false

    container: ruby:3.3.7-alpine3.20

    services:
      postgres:
        image: index.docker.io/postgis/postgis@sha256:681931a625df344215e9b8998bf34daf146b6a395ceacee4439eb9c85869239f
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: postgres
      DATABASE_PASS: postgres
      DATABASE_USER: postgres
      DATABASE_DB_TEST: warehouse_test
      DATABASE_APP_DB_TEST: warehouse_app_test
      DATABASE_WAREHOUSE_DB_TEST: warehouse_test
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: 'Container Setup'
        uses: ./.github/workflows/container_setup

      - name: 'App setup'
        run: |
          cp config/secrets.yml.sample config/secrets.yml
          cp .rspec.sample .rspec
          cp config/database.yml.ci config/database.yml

      - name: Prepare test db
        run: |
          pg_isready -h postgres -U postgres
          bin/db_prep

      - name: Check for overdue TODOs
        run: bundle exec rails test:todo_or_die
